import type {
  BroomReward,
  GameInstruction,
  GameWorld,
  LanguageDomain,
  SceneBuilderInstruction,
  SceneObject,
  SceneZone,
  SpatialConcept,
  TaskDifficulty,
  VocabularyChoiceInstruction,
} from "./types";
const assetPath = (fileName: string) => `assets/objects/transparent/${fileName}`;
export const beachSpatialConcepts: SpatialConcept[] = [
  "in",
  "op",
  "onder",
  "boven",
  "naast",
  "tussen",
  "links",
  "rechts",
  "midden",
  "dichtbij",
  "ver weg",
];
export const beachObjects: SceneObject[] = [
  {
    id: "clown",
    label: "clown",
    pluralLabel: "clowns",
    article: "de",
    category: "artiesten",
    emoji: "🤡",
    assetId: "clown",
    assetPath: assetPath("clown-sticker.png"),
    description: "Een vrolijke clown in de piste.",
    vocabularyLevel: 1,
    tags: ["circus", "artiest", "grappig"],
  },
  {
    id: "acrobaat",
    label: "acrobaat",
    pluralLabel: "acrobaten",
    article: "de",
    category: "artiesten",
    emoji: "🤸",
    assetId: "acrobaat",
    assetPath: assetPath("acrobat-sticker.png"),
    description: "Een acrobaat die door de lucht vliegt.",
    vocabularyLevel: 3,
    tags: ["circus", "artiest", "lucht", "springt"],
  },
  {
    id: "leeuw",
    label: "leeuw",
    pluralLabel: "leeuwen",
    article: "de",
    category: "dieren",
    emoji: "🦁",
    assetId: "leeuw",
    assetPath: assetPath("lion-sticker.png"),
    description: "Een leeuw die door de hoepel springt.",
    vocabularyLevel: 2,
    tags: ["circus", "dier", "brult"],
  },
  {
    id: "olifant",
    label: "olifant",
    pluralLabel: "olifanten",
    article: "de",
    category: "dieren",
    emoji: "🐘",
    assetId: "olifant",
    assetPath: assetPath("elephant-sticker.png"),
    description: "Een grote olifant met een slurf.",
    vocabularyLevel: 2,
    tags: ["circus", "dier", "groot"],
  },
  {
    id: "aap",
    label: "aap",
    pluralLabel: "apen",
    article: "de",
    category: "dieren",
    emoji: "🐵",
    assetId: "aap",
    assetPath: assetPath("monkey-sticker.png"),
    description: "Een aap die klimt en springt.",
    vocabularyLevel: 1,
    tags: ["circus", "dier", "klimt"],
  },
  {
    id: "kip",
    label: "kip",
    pluralLabel: "kippen",
    article: "de",
    category: "dieren",
    emoji: "🐔",
    assetId: "kip",
    assetPath: assetPath("chicken-sticker.png"),
    description: "Een kip die op de vloer tokt.",
    vocabularyLevel: 1,
    tags: ["circus", "dier", "tokt"],
  },
  {
    id: "poes",
    label: "poes",
    pluralLabel: "poezen",
    article: "de",
    category: "dieren",
    emoji: "🐱",
    assetId: "poes",
    assetPath: assetPath("cat-sticker.png"),
    description: "Een poes met zachte pootjes.",
    vocabularyLevel: 1,
    tags: ["circus", "dier", "miauwt"],
  },
  {
    id: "big",
    label: "big",
    pluralLabel: "biggen",
    article: "de",
    category: "dieren",
    emoji: "🐷",
    assetId: "big",
    assetPath: assetPath("piglet-sticker.png"),
    description: "Een klein roze big.",
    vocabularyLevel: 1,
    tags: ["circus", "dier", "roze"],
  },
  {
    id: "muis",
    label: "muis",
    pluralLabel: "muizen",
    article: "de",
    category: "dieren",
    emoji: "🐭",
    assetId: "muis",
    assetPath: assetPath("mouse-sticker.png"),
    description: "Een kleine muis die piept.",
    vocabularyLevel: 1,
    tags: ["circus", "dier", "klein"],
  },
  {
    id: "beer",
    label: "beer",
    pluralLabel: "beren",
    article: "de",
    category: "dieren",
    emoji: "🐻",
    assetId: "beer",
    assetPath: assetPath("bear-sticker.png"),
    description: "Een grote beer met dikke vacht.",
    vocabularyLevel: 2,
    tags: ["circus", "dier", "groot"],
  },
  {
    id: "zeehond",
    label: "zeehond",
    pluralLabel: "zeehonden",
    article: "de",
    category: "dieren",
    emoji: "🦭",
    assetId: "zeehond",
    assetPath: assetPath("seal-sticker.png"),
    description: "Een zeehond die een bal balanceert.",
    vocabularyLevel: 3,
    tags: ["circus", "dier", "balanceert"],
  },
  {
    id: "hond",
    label: "hond",
    pluralLabel: "honden",
    article: "de",
    category: "dieren",
    emoji: "🐕",
    assetId: "hond",
    assetPath: assetPath("dog-sticker.png"),
    description: "Een hond die kunstjes doet.",
    vocabularyLevel: 1,
    tags: ["circus", "dier", "blaft"],
  },
  {
    id: "eenwieler",
    label: "eenwieler",
    pluralLabel: "eenwielers",
    article: "de",
    category: "voertuigen",
    emoji: "🚲",
    assetId: "eenwieler",
    assetPath: assetPath("unicycle-sticker.png"),
    description: "Een eenwieler met één wiel.",
    vocabularyLevel: 3,
    tags: ["circus", "voertuig", "rijdt"],
  },
  {
    id: "kanon",
    label: "kanon",
    pluralLabel: "kanonnen",
    article: "het",
    category: "voertuigen",
    emoji: "💥",
    assetId: "kanon",
    assetPath: assetPath("cannon-sticker.png"),
    description: "Een kanon dat de acrobaat omhoog schiet.",
    vocabularyLevel: 3,
    tags: ["circus", "voertuig", "knalt"],
  },
  {
    id: "bal",
    label: "bal",
    pluralLabel: "ballen",
    article: "de",
    category: "circusspullen",
    emoji: "🔴",
    assetId: "bal",
    assetPath: assetPath("ball-sticker.png"),
    description: "Een bal om mee te jongleren.",
    vocabularyLevel: 1,
    tags: ["circus", "spullen", "rond"],
  },
  {
    id: "hoepel",
    label: "hoepel",
    pluralLabel: "hoepels",
    article: "de",
    category: "circusspullen",
    emoji: "⭕",
    assetId: "hoepel",
    assetPath: assetPath("hoop-sticker.png"),
    description: "Een hoepel om door te springen.",
    vocabularyLevel: 2,
    tags: ["circus", "spullen", "rond"],
  },
  {
    id: "ballon",
    label: "ballon",
    pluralLabel: "ballonnen",
    article: "de",
    category: "circusspullen",
    emoji: "🎈",
    assetId: "ballon",
    assetPath: assetPath("balloon-sticker.png"),
    description: "Een ballon die omhoog zweeft.",
    vocabularyLevel: 1,
    tags: ["circus", "spullen", "zweeft"],
  },
  {
    id: "trommel",
    label: "trommel",
    pluralLabel: "trommels",
    article: "de",
    category: "circusspullen",
    emoji: "🥁",
    assetId: "trommel",
    assetPath: assetPath("drum-sticker.png"),
    description: "Een trommel om muziek op te maken.",
    vocabularyLevel: 2,
    tags: ["circus", "spullen", "muziek"],
  },
  {
    id: "vlag",
    label: "vlag",
    pluralLabel: "vlaggen",
    article: "de",
    category: "decor",
    emoji: "🚩",
    assetId: "vlag",
    assetPath: assetPath("flag-sticker.png"),
    description: "Een vlag die bovenop de tent wappert.",
    vocabularyLevel: 2,
    tags: ["circus", "decor", "wappert"],
  },
];
// Zone-geometrie is 1-op-1 hergebruikt van de strandscène (dezelfde polygonen en
// coördinaten); alleen id, label en beschrijving zijn omgezet naar het circusthema.
export const beachZones: SceneZone[] = [
  // Basisgebied: bovenin de tent (nok)
  {
    id: "nok",
    label: "nok",
    description: "Bovenin de circustent, onder het tentdak.",
    kind: "absolute",
    visualHintPath:
      "M1.9 32.1 L27.7 38.8 L67 38.6 L72.3 31 L81.3 23.8 L98.8 22 L97.8 15.7 L1.5 16.2 Z",
    x: 1.5,
    y: 15.7,
    width: 97.3,
    height: 23.1,
    supportedConcepts: ["boven", "links", "rechts", "midden", "ver weg"],
  },
  // Piste en ringzones
  {
    id: "piste",
    label: "piste",
    description: "De ronde piste midden in de tent.",
    kind: "absolute",
    visualHintPath:
      "M99 52.2 L88.1 52.5 L76.5 54.4 L65 53.8 L55.8 54.6 L44.7 54 L32.3 55.2 L21.4 55.1 L14.3 54 L0.7 53.3 L0.5 38.8 L63.6 39 L59.2 42.1 L76.2 43.2 L99.3 43.8 Z",
    x: 0.5,
    y: 38.8,
    width: 98.8,
    height: 16.4,
    supportedConcepts: ["in", "op", "links", "rechts", "midden", "dichtbij", "ver weg"],
  },
  {
    id: "links-piste",
    label: "links in de piste",
    description: "Linkerkant van de piste.",
    kind: "horizontal",
    visualHintPath: "M1 32.1 L48.8 31.7 L47.5 53.3 L40 54.3 L27.4 55.6 L15.8 53.9 L0.1 53.7 Z",
    x: 0.1,
    y: 31.7,
    width: 48.7,
    height: 23.9,
    supportedConcepts: ["links", "in"],
  },
  {
    id: "boven-piste",
    label: "boven de piste",
    description: "Luchtgebied boven de piste.",
    kind: "relative",
    visualHintPath: "M0.7 31.4 L72.3 31.6 L72.3 16.1 L0.5 16.5 Z",
    x: 0.5,
    y: 16.1,
    width: 71.8,
    height: 15.5,
    supportedConcepts: ["boven", "ver weg"],
  },
  {
    id: "ver-weg-piste",
    label: "ver weg boven de piste",
    description: "Een plek ver weg boven de piste.",
    kind: "relative",
    visualHintPath: "M0 32.1 L0.2 16.5 L64.1 16.1 L64.3 31.6 Z",
    x: 0.0,
    y: 16.1,
    width: 64.3,
    height: 16.0,
    supportedConcepts: ["ver weg", "boven"],
  },
  {
    id: "tribune",
    label: "tribune",
    description: "De tribune met het publiek, rechts in de tent.",
    kind: "landmark",
    visualHintPath:
      "M99.3 43.2 L85.9 43.6 L75 42.8 L60.4 41.9 L64.3 39 L73.3 36.8 L78.4 34.9 L84.2 32.7 L90.3 31.6 L100 30.9 Z",
    x: 60.4,
    y: 30.9,
    width: 39.6,
    height: 12.7,
    supportedConcepts: ["op", "rechts", "ver weg"],
  },
  // Vloer en voorgrondzones
  {
    id: "vloer",
    label: "vloer",
    description: "De vloer op de voorgrond van de scene.",
    kind: "absolute",
    visualHintPath:
      "M0 53.8 L7.8 54.4 L15.3 54.1 L25 55.6 L36.4 55.3 L44.4 54.2 L57 55.1 L66 53.9 L77.9 54.8 L86.2 53.6 L91.7 52.9 L99.5 52.8 L98.8 88 L0.5 88.3 Z",
    x: 0.0,
    y: 52.8,
    width: 99.5,
    height: 35.5,
    supportedConcepts: [
      "op",
      "naast",
      "tussen",
      "links",
      "rechts",
      "midden",
      "dichtbij",
      "ver weg",
    ],
  },
  {
    id: "midden-vloer",
    label: "midden op de vloer",
    description: "Midden van de vloer.",
    kind: "horizontal",
    visualHintPath: "M65.3 53.6 L65.3 88.4 L25.2 88.5 L26.2 55.8 L36.4 55.3 L43.2 54 L54.1 55.4 Z",
    x: 25.2,
    y: 53.6,
    width: 40.1,
    height: 34.9,
    supportedConcepts: ["midden", "op"],
  },
  {
    id: "rechts-vloer",
    label: "rechts op de vloer",
    description: "Rechterkant van de vloer.",
    kind: "horizontal",
    visualHintPath: "M66 53.8 L73.8 54.5 L84 53.9 L92.3 52.5 L100 52.7 L98.8 88.1 L66.3 88.3 Z",
    x: 66.0,
    y: 52.5,
    width: 34.0,
    height: 35.8,
    supportedConcepts: ["rechts", "op"],
  },
  // Relationele zones zoals op/naast/dichtbij/tussen bij een ankerobject
  // worden dynamisch berekend met de actuele positie van geplaatste objecten.
];
const directionDomains: LanguageDomain[] = [
  "sentence-comprehension",
  "concepts-and-directions",
  "spatial-language",
  "following-directions",
];
const getPracticeSentence = (sentence: string) => {
  return sentence.replace(/^(Goed zo!|Mooi!|Ja!|Goed gedaan!)\s*/i, "");
};
const placementFeedback = (sentence: string, concept: SpatialConcept) => ({
  correct: `${sentence} +1 Tempo!`,
  almost: `Bijna! Luister nog eens naar het woord '${concept}'.`,
  tryAgain: "Goed geprobeerd. Kijk rustig naar de plek die oplicht.",
  repeatAfterSuccess: getPracticeSentence(sentence),
});
const choiceFeedback = (word: string, article: "de" | "het") => ({
  correct: `Ja, dat is ${article} ${word}. +1 Tempo!`,
  almost: `Bijna. Zoek nog eens naar: ${word}.`,
  tryAgain: "Goed geprobeerd. Luister nog een keer en kies opnieuw.",
  repeatAfterSuccess: `Dit is ${article} ${word}.`,
});
const sceneTask = (params: {
  id: string;
  level: TaskDifficulty;
  prompt: string;
  objectId: string;
  zoneId: string;
  relation: SpatialConcept;
  anchorObjectIds?: string[];
  hint: string;
  feedbackSentence: string;
  tags?: string[];
}): SceneBuilderInstruction => {
  return {
    id: params.id,
    mode: "listen-and-place",
    level: params.level,
    prompt: params.prompt,
    audioText: params.prompt,
    targetObjectIds: [params.objectId, ...(params.anchorObjectIds ?? [])],
    targetZoneIds: [params.zoneId],
    spatialConcepts: [params.relation],
    languageDomains: directionDomains,
    tags: ["mvp", "scene-builder", params.relation, params.objectId, ...(params.tags ?? [])],
    hint: params.hint,
    feedback: `${params.feedbackSentence} +1 Tempo!`,
    feedbackCopy: placementFeedback(params.feedbackSentence, params.relation),
    placement: {
      objectId: params.objectId,
      zoneId: params.zoneId,
      relation: params.relation,
      anchorObjectIds: params.anchorObjectIds,
    },
    reward: { speed: 1, wordStars: 1 },
  };
};
const choiceTask = (params: {
  id: string;
  level: TaskDifficulty;
  prompt: string;
  objectId: string;
  options: string[];
  hint: string;
  distractorStrategy: VocabularyChoiceInstruction["distractorStrategy"];
}): VocabularyChoiceInstruction => {
  const target = beachObjects.find((object) => object.id === params.objectId);
  const targetWord = target?.label ?? params.objectId;
  const article = target?.article ?? "de";
  return {
    id: params.id,
    mode: "choose-word",
    level: params.level,
    prompt: params.prompt,
    audioText: params.prompt,
    targetObjectIds: [params.objectId],
    targetZoneIds: [],
    spatialConcepts: [],
    languageDomains: ["receptive-vocabulary"],
    tags: ["mvp", "choose-word", "receptive-vocabulary", params.objectId],
    hint: params.hint,
    feedback: `Ja, dat is ${article} ${targetWord}. +1 Tempo!`,
    feedbackCopy: choiceFeedback(targetWord, article),
    targetWord,
    answerOptions: params.options,
    choiceCount: params.options.length as 2 | 3 | 4,
    distractorStrategy: params.distractorStrategy,
    reward: { speed: 1, wordStars: 1 },
  };
};
export const sceneBuilderInstructions: SceneBuilderInstruction[] = [
  sceneTask({
    id: "lp-001",
    level: 1,
    prompt: "Zet de eenwieler in de piste.",
    objectId: "eenwieler",
    zoneId: "piste",
    relation: "in",
    hint: "Zoek de eenwieler en sleep hem naar de piste.",
    feedbackSentence: "Goed zo! De eenwieler staat in de piste.",
  }),
  sceneTask({
    id: "lp-002",
    level: 1,
    prompt: "Zet de leeuw in de piste.",
    objectId: "leeuw",
    zoneId: "piste",
    relation: "in",
    hint: "De leeuw doet zijn kunstje in de piste.",
    feedbackSentence: "Mooi! De leeuw staat in de piste.",
  }),
  sceneTask({
    id: "lp-003",
    level: 1,
    prompt: "Leg de bal op de vloer.",
    objectId: "bal",
    zoneId: "vloer",
    relation: "op",
    hint: "De bal hoort op de vloer.",
    feedbackSentence: "Ja! De bal ligt op de vloer.",
  }),
  sceneTask({
    id: "lp-004",
    level: 1,
    prompt: "Zet de vlag op de tribune.",
    objectId: "vlag",
    zoneId: "tribune",
    relation: "op",
    hint: "Kijk naar de tribune rechts in de tent.",
    feedbackSentence: "Goed gedaan! De vlag staat op de tribune.",
  }),
  sceneTask({
    id: "lp-005",
    level: 1,
    prompt: "Zet de ballon boven in de nok.",
    objectId: "ballon",
    zoneId: "nok",
    relation: "boven",
    hint: "De ballon zweeft hoog in de nok.",
    feedbackSentence: "Goed zo! De ballon zweeft boven in de nok.",
  }),
  sceneTask({
    id: "lp-006",
    level: 1,
    prompt: "Zet het kanon boven de piste.",
    objectId: "kanon",
    zoneId: "boven-piste",
    relation: "boven",
    hint: "Boven de piste is in de lucht.",
    feedbackSentence: "Knap! Het kanon staat boven de piste.",
  }),
  sceneTask({
    id: "lp-007",
    level: 1,
    prompt: "Zet de hoepel op de vloer.",
    objectId: "hoepel",
    zoneId: "vloer",
    relation: "op",
    hint: "De hoepel ligt op de vloer.",
    feedbackSentence: "Ja! De hoepel ligt op de vloer.",
  }),
  sceneTask({
    id: "lp-008",
    level: 1,
    prompt: "Zet de aap op de trommel.",
    objectId: "aap",
    zoneId: "op-trommel",
    relation: "op",
    anchorObjectIds: ["trommel"],
    hint: "Zoek de trommel en zet de aap erop.",
    feedbackSentence: "Goed! De aap zit op de trommel.",
  }),
  sceneTask({
    id: "lp-009",
    level: 2,
    prompt: "Zet de clown naast de hoepel.",
    objectId: "clown",
    zoneId: "naast-hoepel",
    relation: "naast",
    anchorObjectIds: ["hoepel"],
    hint: "Naast betekent dichtbij aan de zijkant.",
    feedbackSentence: "Mooi! De clown staat naast de hoepel.",
  }),
  sceneTask({
    id: "lp-010",
    level: 2,
    prompt: "Zet de olifant rechts op de vloer.",
    objectId: "olifant",
    zoneId: "rechts-vloer",
    relation: "rechts",
    hint: "Rechts is de kant van je rechterhand.",
    feedbackSentence: "Ja! De olifant staat rechts op de vloer.",
  }),
  sceneTask({
    id: "lp-011",
    level: 2,
    prompt: "Zet de acrobaat boven de piste.",
    objectId: "acrobaat",
    zoneId: "boven-piste",
    relation: "boven",
    hint: "De acrobaat vliegt hoog boven de piste.",
    feedbackSentence: "Knap! De acrobaat vliegt boven de piste.",
  }),
  sceneTask({
    id: "lp-012",
    level: 2,
    prompt: "Leg de trommel midden op de vloer.",
    objectId: "trommel",
    zoneId: "midden-vloer",
    relation: "midden",
    hint: "Midden is niet links en niet rechts.",
    feedbackSentence: "Knap! De trommel staat midden op de vloer.",
  }),
  sceneTask({
    id: "lp-013",
    level: 2,
    prompt: "Zet de eenwieler links in de piste.",
    objectId: "eenwieler",
    zoneId: "links-piste",
    relation: "links",
    hint: "Links is de kant van je linkerhand.",
    feedbackSentence: "Goed! De eenwieler rijdt links in de piste.",
  }),
  sceneTask({
    id: "lp-014",
    level: 3,
    prompt: "Zet het kanon ver weg boven de piste.",
    objectId: "kanon",
    zoneId: "ver-weg-piste",
    relation: "ver weg",
    hint: "Ver weg is verder van de voorkant van de scene.",
    feedbackSentence: "Mooi! Het kanon staat ver weg boven de piste.",
  }),
  sceneTask({
    id: "lp-015",
    level: 3,
    prompt: "Leg de bal dichtbij de hoepel.",
    objectId: "bal",
    zoneId: "dichtbij-hoepel",
    relation: "dichtbij",
    anchorObjectIds: ["hoepel"],
    hint: "Dichtbij betekent niet ver weg.",
    feedbackSentence: "Ja! De bal ligt dichtbij de hoepel.",
  }),
  sceneTask({
    id: "lp-016",
    level: 3,
    prompt: "Leg de hoepel tussen de bal en de ballon.",
    objectId: "hoepel",
    zoneId: "tussen-bal-ballon",
    relation: "tussen",
    anchorObjectIds: ["bal", "ballon"],
    hint: "Tussen betekent in het midden van twee dingen.",
    feedbackSentence: "Knap! De hoepel ligt tussen de bal en de ballon.",
  }),
  sceneTask({
    id: "lp-017",
    level: 1,
    prompt: "Zet de hond op de vloer.",
    objectId: "hond",
    zoneId: "vloer",
    relation: "op",
    hint: "De hond staat op de vloer.",
    feedbackSentence: "Goed zo! De hond staat op de vloer.",
  }),
  sceneTask({
    id: "lp-018",
    level: 1,
    prompt: "Zet de zeehond in de piste.",
    objectId: "zeehond",
    zoneId: "piste",
    relation: "in",
    hint: "De zeehond doet zijn kunstje in de piste.",
    feedbackSentence: "Mooi! De zeehond zit in de piste.",
  }),
  sceneTask({
    id: "lp-019",
    level: 2,
    prompt: "Zet de poes op de trommel.",
    objectId: "poes",
    zoneId: "op-trommel-poes",
    relation: "op",
    anchorObjectIds: ["trommel"],
    hint: "Zoek de trommel en zet de poes erop.",
    feedbackSentence: "Goed! De poes zit op de trommel.",
  }),
  sceneTask({
    id: "lp-020",
    level: 2,
    prompt: "Zet de muis naast de bal.",
    objectId: "muis",
    zoneId: "naast-bal",
    relation: "naast",
    anchorObjectIds: ["bal"],
    hint: "Naast betekent dichtbij aan de zijkant.",
    feedbackSentence: "Mooi! De muis zit naast de bal.",
  }),
  sceneTask({
    id: "lp-021",
    level: 2,
    prompt: "Zet de big rechts op de vloer.",
    objectId: "big",
    zoneId: "rechts-vloer",
    relation: "rechts",
    hint: "Rechts is de kant van je rechterhand.",
    feedbackSentence: "Ja! De big staat rechts op de vloer.",
  }),
  sceneTask({
    id: "lp-022",
    level: 3,
    prompt: "Zet de kip tussen de hoepel en de bal.",
    objectId: "kip",
    zoneId: "tussen-hoepel-bal",
    relation: "tussen",
    anchorObjectIds: ["hoepel", "bal"],
    hint: "Tussen betekent in het midden van twee dingen.",
    feedbackSentence: "Knap! De kip staat tussen de hoepel en de bal.",
  }),
  sceneTask({
    id: "lp-023",
    level: 3,
    prompt: "Zet de beer dichtbij de trommel.",
    objectId: "beer",
    zoneId: "dichtbij-trommel",
    relation: "dichtbij",
    anchorObjectIds: ["trommel"],
    hint: "Dichtbij betekent niet ver weg.",
    feedbackSentence: "Ja! De beer staat dichtbij de trommel.",
  }),
];
export const vocabularyChoiceInstructions: VocabularyChoiceInstruction[] = [
  choiceTask({
    id: "cw-001",
    level: 1,
    prompt: "Waar is de leeuw?",
    objectId: "leeuw",
    options: ["leeuw", "eenwieler"],
    hint: "De leeuw is het dier dat brult.",
    distractorStrategy: "different-category",
  }),
  choiceTask({
    id: "cw-002",
    level: 1,
    prompt: "Waar is de eenwieler?",
    objectId: "eenwieler",
    options: ["eenwieler", "bal"],
    hint: "Op een eenwieler rijd je met één wiel.",
    distractorStrategy: "different-category",
  }),
  choiceTask({
    id: "cw-003",
    level: 1,
    prompt: "Waar is de bal?",
    objectId: "bal",
    options: ["bal", "hoepel"],
    hint: "Met een bal kun je gooien of jongleren.",
    distractorStrategy: "same-theme",
  }),
  choiceTask({
    id: "cw-004",
    level: 2,
    prompt: "Waar is de olifant?",
    objectId: "olifant",
    options: ["olifant", "leeuw", "vlag"],
    hint: "De olifant is groot en heeft een slurf.",
    distractorStrategy: "same-theme",
  }),
  choiceTask({
    id: "cw-005",
    level: 2,
    prompt: "Waar is de ballon?",
    objectId: "ballon",
    options: ["ballon", "hoepel", "aap"],
    hint: "Een ballon zweeft omhoog in de lucht.",
    distractorStrategy: "same-theme",
  }),
  choiceTask({
    id: "cw-006",
    level: 2,
    prompt: "Waar is de clown?",
    objectId: "clown",
    options: ["clown", "acrobaat", "eenwieler"],
    hint: "De clown maakt grappen en lacht.",
    distractorStrategy: "same-theme",
  }),
  choiceTask({
    id: "cw-007",
    level: 2,
    prompt: "Waar is de aap?",
    objectId: "aap",
    options: ["aap", "leeuw", "hoepel"],
    hint: "De aap klimt en springt graag.",
    distractorStrategy: "same-category",
  }),
  choiceTask({
    id: "cw-008",
    level: 2,
    prompt: "Waar is de trommel?",
    objectId: "trommel",
    options: ["trommel", "ballon", "bal"],
    hint: "Op een trommel maak je muziek.",
    distractorStrategy: "same-category",
  }),
  choiceTask({
    id: "cw-009",
    level: 3,
    prompt: "Waar is de hoepel?",
    objectId: "hoepel",
    options: ["hoepel", "aap", "bal", "ballon"],
    hint: "Door een hoepel kun je springen.",
    distractorStrategy: "same-theme",
  }),
  choiceTask({
    id: "cw-010",
    level: 3,
    prompt: "Waar is de vlag?",
    objectId: "vlag",
    options: ["vlag", "kanon", "ballon", "bal"],
    hint: "Een vlag wappert bovenop de tent.",
    distractorStrategy: "same-theme",
  }),
  choiceTask({
    id: "cw-011",
    level: 3,
    prompt: "Waar is het kanon?",
    objectId: "kanon",
    options: ["kanon", "eenwieler", "leeuw", "clown"],
    hint: "Uit een kanon schiet de acrobaat omhoog.",
    distractorStrategy: "same-category",
  }),
  choiceTask({
    id: "cw-012",
    level: 3,
    prompt: "Waar is de acrobaat?",
    objectId: "acrobaat",
    options: ["acrobaat", "clown", "olifant", "aap"],
    hint: "De acrobaat maakt mooie sprongen in de lucht.",
    distractorStrategy: "same-category",
  }),
  choiceTask({
    id: "cw-013",
    level: 1,
    prompt: "Waar is de hond?",
    objectId: "hond",
    options: ["hond", "kip"],
    hint: "De hond blaft en kwispelt met zijn staart.",
    distractorStrategy: "different-category",
  }),
  choiceTask({
    id: "cw-014",
    level: 1,
    prompt: "Waar is de poes?",
    objectId: "poes",
    options: ["poes", "muis"],
    hint: "De poes miauwt en heeft zachte pootjes.",
    distractorStrategy: "same-category",
  }),
  choiceTask({
    id: "cw-015",
    level: 2,
    prompt: "Waar is de big?",
    objectId: "big",
    options: ["big", "beer", "hond"],
    hint: "De big is een klein roze varken.",
    distractorStrategy: "same-category",
  }),
  choiceTask({
    id: "cw-016",
    level: 2,
    prompt: "Waar is de muis?",
    objectId: "muis",
    options: ["muis", "kip", "poes"],
    hint: "De muis is heel klein en piept.",
    distractorStrategy: "same-category",
  }),
  choiceTask({
    id: "cw-017",
    level: 2,
    prompt: "Waar is de beer?",
    objectId: "beer",
    options: ["beer", "leeuw", "hond"],
    hint: "De beer is groot en heeft dikke vacht.",
    distractorStrategy: "same-category",
  }),
  choiceTask({
    id: "cw-018",
    level: 2,
    prompt: "Waar is de kip?",
    objectId: "kip",
    options: ["kip", "poes", "muis"],
    hint: "De kip legt eieren en tokt.",
    distractorStrategy: "same-category",
  }),
  choiceTask({
    id: "cw-019",
    level: 3,
    prompt: "Waar is de zeehond?",
    objectId: "zeehond",
    options: ["zeehond", "hond", "big", "poes"],
    hint: "De zeehond klapt en balanceert een bal.",
    distractorStrategy: "same-category",
  }),
];
export const beachInstructions: GameInstruction[] = [
  ...sceneBuilderInstructions,
  ...vocabularyChoiceInstructions,
];
export const beachRewards: BroomReward[] = [
  {
    id: "red-broom",
    type: "broom",
    name: "Rode Bezem",
    description: "Een vrolijke rode circusbezem.",
    assetId: "broom-01-basic",
    unlockAfterWordStars: 5,
  },
  {
    id: "leeuw-sticker",
    type: "sticker",
    name: "Leeuw Sticker",
    description: "Een dappere leeuwsticker voor het stickerboek.",
    assetId: "leeuw",
    unlockAfterWordStars: 10,
  },
  {
    id: "circus-trail",
    type: "broom-trail",
    name: "Circus Sprankel",
    description: "Een glinsterende circustrail achter de bezem.",
    assetId: "broom-02-beach",
    unlockAfterWordStars: 15,
  },
  {
    id: "star-mascot-badge",
    type: "sticker",
    name: "Ster Helper",
    description: "Een mascottesticker voor goede oefenrondes.",
    assetId: "mascot-07-ui-icon",
    unlockAfterWordStars: 20,
  },
];
export const beachWorld: GameWorld = {
  id: "circus-world-1",
  name: "Circuswereld",
  theme: "circus",
  recommendedAgeLabel: "4-7 jaar",
  spatialConcepts: beachSpatialConcepts,
  objects: beachObjects,
  zones: beachZones,
  instructions: beachInstructions,
  rewards: beachRewards,
};
export const firstDemoInstructionIds = beachInstructions.map((instruction) => instruction.id);
