import type {
  BroomRaceInstruction,
  BroomReward,
  GameInstruction,
  GameWorld,
  LanguageDomain,
  SceneBuilderInstruction,
  SceneObject,
  SceneZone,
  SpatialConcept,
  TaskDifficulty,
  VocabularyChoiceInstruction,
} from "./types";

const assetPath = (fileName: string) =>
  `assets/objects/transparent/${fileName}`;

export const beachSpatialConcepts: SpatialConcept[] = [
  "in",
  "op",
  "onder",
  "boven",
  "naast",
  "tussen",
  "links",
  "rechts",
  "midden",
  "dichtbij",
  "ver weg",
];

export const beachObjects: SceneObject[] = [
  {
    id: "dolfijn",
    label: "dolfijn",
    pluralLabel: "dolfijnen",
    article: "de",
    category: "dieren",
    emoji: "🐬",
    assetId: "dolfijn",
    assetPath: assetPath("dolphin-sticker.png"),
    description: "Een dolfijn die in de zee zwemt.",
    vocabularyLevel: 2,
    tags: ["strand", "dier", "zee", "beweegt"],
  },
  {
    id: "boot",
    label: "boot",
    pluralLabel: "boten",
    article: "de",
    category: "voertuigen",
    emoji: "⛵",
    assetId: "boot",
    assetPath: assetPath("sailboat-sticker.png"),
    description: "Een kleine boot op het water.",
    vocabularyLevel: 1,
    tags: ["strand", "voertuig", "zee", "vaart"],
  },
  {
    id: "vuurtoren",
    label: "vuurtoren",
    pluralLabel: "vuurtorens",
    article: "de",
    category: "plekken",
    emoji: "🗼",
    assetId: "vuurtoren",
    assetPath: assetPath("lighthouse-sticker.png"),
    description: "Een hoge toren op het eiland.",
    vocabularyLevel: 3,
    tags: ["strand", "plek", "eiland", "hoog"],
  },
  {
    id: "vliegtuig",
    label: "vliegtuig",
    pluralLabel: "vliegtuigen",
    article: "het",
    category: "voertuigen",
    emoji: "✈️",
    assetId: "vliegtuig",
    assetPath: assetPath("airplane-sticker.png"),
    description: "Een vliegtuig in de lucht.",
    vocabularyLevel: 2,
    tags: ["lucht", "voertuig", "vliegt"],
  },
  {
    id: "vlieger",
    label: "vlieger",
    pluralLabel: "vliegers",
    article: "de",
    category: "strandspullen",
    emoji: "🪁",
    assetId: "vlieger",
    assetPath: assetPath("kite-sticker.png"),
    description: "Een vlieger boven het strand.",
    vocabularyLevel: 2,
    tags: ["strand", "speelgoed", "lucht"],
  },
  {
    id: "bal",
    label: "bal",
    pluralLabel: "ballen",
    article: "de",
    category: "strandspullen",
    emoji: "⚽",
    assetId: "bal",
    assetPath: assetPath("beach-ball-sticker.png"),
    description: "Een bal op het strand.",
    vocabularyLevel: 1,
    tags: ["strand", "speelgoed", "rond"],
  },
  {
    id: "parasol",
    label: "parasol",
    pluralLabel: "parasols",
    article: "de",
    category: "strandspullen",
    emoji: "⛱️",
    assetId: "parasol",
    assetPath: assetPath("beach-umbrella-sticker.png"),
    description: "Een parasol die schaduw geeft.",
    vocabularyLevel: 2,
    tags: ["strand", "spullen", "schaduw"],
  },
  {
    id: "schelp",
    label: "schelp",
    pluralLabel: "schelpen",
    article: "de",
    category: "strandspullen",
    emoji: "🐚",
    assetId: "schelp",
    assetPath: assetPath("seashells-sticker.png"),
    description: "Een schelp op het zand.",
    vocabularyLevel: 2,
    tags: ["strand", "spullen", "zee"],
  },
  {
    id: "krab",
    label: "krab",
    pluralLabel: "krabben",
    article: "de",
    category: "dieren",
    emoji: "🦀",
    assetId: "krab",
    assetPath: assetPath("crab-sticker.png"),
    description: "Een krab op het strand.",
    vocabularyLevel: 2,
    tags: ["strand", "dier", "scharen"],
  },
  {
    id: "zandkasteel",
    label: "zandkasteel",
    pluralLabel: "zandkastelen",
    article: "het",
    category: "strandspullen",
    emoji: "🏰",
    assetId: "zandkasteel",
    assetPath: assetPath("sandcastle-sticker.png"),
    description: "Een kasteel van zand.",
    vocabularyLevel: 2,
    tags: ["strand", "spullen", "zand"],
  },
  {
    id: "handdoek",
    label: "handdoek",
    pluralLabel: "handdoeken",
    article: "de",
    category: "strandspullen",
    emoji: "▤",
    assetId: "handdoek",
    assetPath: assetPath("beach-towel-sticker.png"),
    description: "Een zachte handdoek op het strand.",
    vocabularyLevel: 1,
    tags: ["strand", "spullen", "liggen"],
  },
  {
    id: "zon",
    label: "zon",
    pluralLabel: "zonnen",
    article: "de",
    category: "natuur",
    emoji: "☀️",
    assetId: "zon",
    assetPath: assetPath("sun-sticker.png"),
    description: "De zon boven de zee.",
    vocabularyLevel: 1,
    tags: ["lucht", "natuur", "warm"],
  },
];

export const beachZones: SceneZone[] = [
  // Basisgebied: lucht
  {
    id: "lucht",
    label: "lucht",
    description: "De lucht boven de zee en het strand.",
    kind: "absolute",
    visualHintPath:
      "M0.9 31.6 L71.3 31.1 L77.2 28.3 L81.7 24.5 L77.8 20.7 L76 15.3 L82 10.6 L89.2 10.6 L90.7 4.9 L94.9 0.7 L86.2 0 L6 0.9 L0.9 4.7 Z",
    x: 0,
    y: 0,
    width: 100,
    height: 38,
    supportedConcepts: ["boven", "links", "rechts", "midden", "ver weg"],
  },

  // Zee en waterzones
  {
    id: "zee",
    label: "zee",
    description: "Het watergebied in de scene.",
    kind: "absolute",
    visualHintPath:
      "M0.5 57.5 L8.9 58.2 L18.2 59.6 L26.9 59.6 L35.8 58.7 L44.3 58 L53.6 60.1 L64.2 59.6 L71 57.5 L77.2 57.9 L84.5 58.9 L91.4 57.1 L99.2 57.5 L99.7 40.7 L92.2 40 L86.4 39.1 L80.3 38.4 L71.1 38.4 L60.8 37.1 L66.1 33.7 L70.4 30.1 L0.4 31.7 Z",
    x: 0,
    y: 38,
    width: 100,
    height: 30,
    supportedConcepts: [
      "in",
      "op",
      "links",
      "rechts",
      "midden",
      "dichtbij",
      "ver weg",
    ],
  },
  {
    id: "links-zee",
    label: "links in zee",
    description: "Linkerkant van de zee.",
    kind: "horizontal",
    visualHintPath:
      "M0.9 32 L40.8 31.6 L40.8 58 L30.8 60.3 L23 60.9 L16 60.2 L7.8 58 L1.3 58.1 L0 54.5 Z",
    x: 4,
    y: 42,
    width: 28,
    height: 22,
    supportedConcepts: ["links", "in"],
  },
  {
    id: "boven-zee",
    label: "boven de zee",
    description: "Luchtgebied boven de zee.",
    kind: "relative",
    visualHintPath: "M0.6 31.2 L72.5 30.9 L72.5 14.3 L0.6 14.3 Z",
    x: 12,
    y: 10,
    width: 76,
    height: 24,
    supportedConcepts: ["boven", "ver weg"],
  },
  {
    id: "ver-weg-zee",
    label: "ver weg boven zee",
    description: "Een plek ver weg in de lucht boven de zee.",
    kind: "relative",
    visualHintPath: "M0.7 16.9 L10.5 18.7 L18.6 24 L21.9 31.3 L0.9 32 Z",
    x: 70,
    y: 8,
    width: 22,
    height: 18,
    supportedConcepts: ["ver weg", "boven"],
  },
  {
    id: "eiland",
    label: "eiland",
    description: "Klein eiland rechts in de zee.",
    kind: "landmark",
    visualHintPath:
      "M61.4 36.5 L70.4 37.9 L84.7 38.6 L94.9 38.6 L98.8 39.8 L98.8 26.4 L85 27.6 L74.3 30.1 L66.8 33.4 Z",
    x: 68,
    y: 42,
    width: 24,
    height: 18,
    supportedConcepts: ["op", "rechts", "ver weg"],
  },

  // Strand en zandzones
  {
    id: "strand",
    label: "strand",
    description: "Het zandgebied onderaan de scene.",
    kind: "absolute",
    visualHintPath:
      "M1.8 58.6 L8.4 57.7 L15.9 61.5 L30.2 61.7 L39.8 60.8 L44.9 59.6 L55.1 61 L66.2 59.8 L74.6 58.4 L85.6 59.8 L95.8 58.2 L98.8 59.8 L99.7 95.9 L93.4 99.2 L5.4 99.9 L0 96.1 Z",
    x: 0,
    y: 66,
    width: 100,
    height: 34,
    supportedConcepts: [
      "op",
      "naast",
      "tussen",
      "links",
      "rechts",
      "midden",
      "dichtbij",
      "ver weg",
    ],
  },
  {
    id: "midden-strand",
    label: "midden op het strand",
    description: "Midden van het strand.",
    kind: "horizontal",
    visualHintPath:
      "M24.6 61.7 L23.7 99.4 L69.8 99.2 L71.3 59.1 L60.2 60.3 L42.2 59.3 Z",
    x: 36,
    y: 72,
    width: 28,
    height: 22,
    supportedConcepts: ["midden", "op"],
  },
  {
    id: "rechts-strand",
    label: "rechts op het strand",
    description: "Rechterkant van het strand.",
    kind: "horizontal",
    visualHintPath:
      "M71.6 57.9 L69.5 99.2 L95.2 99.6 L99.4 97.3 L99.4 56.5 L89.5 59.3 L79.9 59.1 Z",
    x: 66,
    y: 72,
    width: 28,
    height: 22,
    supportedConcepts: ["rechts", "op"],
  },
  {
    id: "handdoek-zone",
    label: "handdoek",
    description: "Plek op de handdoek.",
    kind: "landmark",
    visualHintPath:
      "M99.7 64.6 L99.8 98.5 L99.1 99.6 L97.8 99.9 L1.4 99.8 L0.3 99.3 L0.1 95.7 L0.1 67.9 L14.4 66.7 L51 66 L79.6 65.4 Z",
    x: 60,
    y: 76,
    width: 24,
    height: 18,
    supportedConcepts: ["op", "onder", "naast"],
  },

  // Relationele zones zoals naast/dichtbij/tussen worden dynamisch berekend
  // met de actuele positie van geplaatste objecten.
];

const directionDomains: LanguageDomain[] = [
  "sentence-comprehension",
  "concepts-and-directions",
  "spatial-language",
  "following-directions",
];

function getPracticeSentence(sentence: string) {
  return sentence.replace(/^(Goed zo!|Mooi!|Ja!|Goed gedaan!)\s*/i, "");
}

const placementFeedback = (sentence: string, concept: SpatialConcept) => ({
  correct: `${sentence} +1 Speed!`,
  almost: `Bijna! Luister nog eens naar het woord '${concept}'.`,
  tryAgain: "Goed geprobeerd. Kijk rustig naar de plek die oplicht.",
  repeatAfterSuccess: getPracticeSentence(sentence),
});

const choiceFeedback = (word: string) => ({
  correct: `Ja, dat is de ${word}. +1 Speed!`,
  almost: `Bijna. Zoek nog eens naar: ${word}.`,
  tryAgain: "Goed geprobeerd. Luister nog een keer en kies opnieuw.",
  repeatAfterSuccess: `Dit is de ${word}.`,
});

function sceneTask(params: {
  id: string;
  level: TaskDifficulty;
  prompt: string;
  objectId: string;
  zoneId: string;
  relation: SpatialConcept;
  anchorObjectIds?: string[];
  hint: string;
  feedbackSentence: string;
  tags?: string[];
}): SceneBuilderInstruction {
  return {
    id: params.id,
    mode: "listen-and-place",
    level: params.level,
    prompt: params.prompt,
    audioText: params.prompt,
    targetObjectIds: [params.objectId, ...(params.anchorObjectIds ?? [])],
    targetZoneIds: [params.zoneId],
    spatialConcepts: [params.relation],
    languageDomains: directionDomains,
    tags: [
      "mvp",
      "scene-builder",
      params.relation,
      params.objectId,
      ...(params.tags ?? []),
    ],
    hint: params.hint,
    feedback: `${params.feedbackSentence} +1 Speed!`,
    feedbackCopy: placementFeedback(params.feedbackSentence, params.relation),
    placement: {
      objectId: params.objectId,
      zoneId: params.zoneId,
      relation: params.relation,
      anchorObjectIds: params.anchorObjectIds,
    },
    reward: { speed: 1, wordStars: 1 },
  };
}

function choiceTask(params: {
  id: string;
  level: TaskDifficulty;
  prompt: string;
  objectId: string;
  options: string[];
  hint: string;
  distractorStrategy: VocabularyChoiceInstruction["distractorStrategy"];
}): VocabularyChoiceInstruction {
  const target = beachObjects.find((object) => object.id === params.objectId);
  const targetWord = target?.label ?? params.objectId;

  return {
    id: params.id,
    mode: "choose-word",
    level: params.level,
    prompt: params.prompt,
    audioText: params.prompt,
    targetObjectIds: [params.objectId],
    targetZoneIds: [],
    spatialConcepts: [],
    languageDomains: ["receptive-vocabulary"],
    tags: ["mvp", "choose-word", "receptive-vocabulary", params.objectId],
    hint: params.hint,
    feedback: `Ja, dat is de ${targetWord}. +1 Speed!`,
    feedbackCopy: choiceFeedback(targetWord),
    targetWord,
    answerOptions: params.options,
    choiceCount: params.options.length as 2 | 3 | 4,
    distractorStrategy: params.distractorStrategy,
    reward: { speed: 1, wordStars: 1 },
  };
}

function raceTask(params: {
  id: string;
  level: TaskDifficulty;
  prompt: string;
  objectIds: string[];
  zoneIds: string[];
  concepts: SpatialConcept[];
  raceAction: BroomRaceInstruction["raceAction"];
  hint: string;
  feedbackSentence: string;
  tags?: string[];
}): BroomRaceInstruction {
  return {
    id: params.id,
    mode: "broom-escape-run",
    level: params.level,
    prompt: params.prompt,
    audioText: params.prompt,
    targetObjectIds: params.objectIds,
    targetZoneIds: params.zoneIds,
    spatialConcepts: params.concepts,
    languageDomains: directionDomains,
    tags: [
      "mvp",
      "race",
      ...params.concepts,
      ...params.objectIds,
      ...(params.tags ?? []),
    ],
    hint: params.hint,
    feedback: `${params.feedbackSentence} +1 Speed!`,
    feedbackCopy: placementFeedback(
      params.feedbackSentence,
      params.concepts[0] ?? "op",
    ),
    raceAction: params.raceAction,
    durationSeconds: 30,
    reward: { speed: 1, wordStars: 1 },
  };
}

export const sceneBuilderInstructions: SceneBuilderInstruction[] = [
  sceneTask({
    id: "lp-001",
    level: 1,
    prompt: "Zet de boot in de zee.",
    objectId: "boot",
    zoneId: "zee",
    relation: "in",
    hint: "Zoek de boot en sleep hem naar het water.",
    feedbackSentence: "Goed zo! De boot vaart in de zee.",
  }),
  sceneTask({
    id: "lp-002",
    level: 1,
    prompt: "Zet de dolfijn in de zee.",
    objectId: "dolfijn",
    zoneId: "zee",
    relation: "in",
    hint: "De dolfijn zwemt in het water.",
    feedbackSentence: "Mooi! De dolfijn zwemt in de zee.",
  }),
  sceneTask({
    id: "lp-003",
    level: 1,
    prompt: "Zet de bal op het strand.",
    objectId: "bal",
    zoneId: "strand",
    relation: "op",
    hint: "De bal hoort op het zand.",
    feedbackSentence: "Ja! De bal ligt op het strand.",
  }),
  sceneTask({
    id: "lp-004",
    level: 1,
    prompt: "Zet de vuurtoren op het eiland.",
    objectId: "vuurtoren",
    zoneId: "eiland",
    relation: "op",
    hint: "Kijk naar het eiland rechts in de zee.",
    feedbackSentence: "Goed gedaan! De vuurtoren staat op het eiland.",
  }),
  sceneTask({
    id: "lp-005",
    level: 1,
    prompt: "Zet de vlieger boven het strand.",
    objectId: "vlieger",
    zoneId: "lucht",
    relation: "boven",
    hint: "De vlieger hoort hoog in de lucht.",
    feedbackSentence: "Goed zo! De vlieger is boven het strand.",
  }),
  sceneTask({
    id: "lp-006",
    level: 1,
    prompt: "Zet het vliegtuig boven de zee.",
    objectId: "vliegtuig",
    zoneId: "boven-zee",
    relation: "boven",
    hint: "Boven de zee is in de lucht.",
    feedbackSentence: "Knap! Het vliegtuig vliegt boven de zee.",
  }),
  sceneTask({
    id: "lp-007",
    level: 1,
    prompt: "Leg de schelp op het strand.",
    objectId: "schelp",
    zoneId: "strand",
    relation: "op",
    hint: "De schelp ligt op het zand.",
    feedbackSentence: "Ja! De schelp ligt op het strand.",
  }),
  sceneTask({
    id: "lp-008",
    level: 1,
    prompt: "Zet de krab op de handdoek.",
    objectId: "krab",
    zoneId: "handdoek-zone",
    relation: "op",
    anchorObjectIds: ["handdoek"],
    hint: "Zoek de handdoek en zet de krab erop.",
    feedbackSentence: "Goed! De krab zit op de handdoek.",
  }),
  sceneTask({
    id: "lp-009",
    level: 2,
    prompt: "Zet het zandkasteel naast de schelp.",
    objectId: "zandkasteel",
    zoneId: "naast-schelp",
    relation: "naast",
    anchorObjectIds: ["schelp"],
    hint: "Naast betekent dichtbij aan de zijkant.",
    feedbackSentence: "Mooi! Het zandkasteel staat naast de schelp.",
  }),
  sceneTask({
    id: "lp-010",
    level: 2,
    prompt: "Zet de parasol rechts op het strand.",
    objectId: "parasol",
    zoneId: "rechts-strand",
    relation: "rechts",
    hint: "Rechts is de kant van je rechterhand.",
    feedbackSentence: "Ja! De parasol staat rechts op het strand.",
  }),
  sceneTask({
    id: "lp-011",
    level: 2,
    prompt: "Zet de zon boven de zee.",
    objectId: "zon",
    zoneId: "boven-zee",
    relation: "boven",
    hint: "De zon staat hoog in de lucht.",
    feedbackSentence: "Goed zo! De zon staat boven de zee.",
  }),
  sceneTask({
    id: "lp-012",
    level: 2,
    prompt: "Leg de handdoek midden op het strand.",
    objectId: "handdoek",
    zoneId: "midden-strand",
    relation: "midden",
    hint: "Midden is niet links en niet rechts.",
    feedbackSentence: "Knap! De handdoek ligt midden op het strand.",
  }),
  sceneTask({
    id: "lp-013",
    level: 2,
    prompt: "Zet de boot links in de zee.",
    objectId: "boot",
    zoneId: "links-zee",
    relation: "links",
    hint: "Links is de kant van je linkerhand.",
    feedbackSentence: "Goed! De boot vaart links in de zee.",
  }),
  sceneTask({
    id: "lp-014",
    level: 3,
    prompt: "Zet het vliegtuig ver weg boven de zee.",
    objectId: "vliegtuig",
    zoneId: "ver-weg-zee",
    relation: "ver weg",
    hint: "Ver weg is verder van de voorkant van de scene.",
    feedbackSentence: "Mooi! Het vliegtuig vliegt ver weg boven de zee.",
  }),
  sceneTask({
    id: "lp-015",
    level: 3,
    prompt: "Leg de bal dichtbij de parasol.",
    objectId: "bal",
    zoneId: "dichtbij-parasol",
    relation: "dichtbij",
    anchorObjectIds: ["parasol"],
    hint: "Dichtbij betekent niet ver weg.",
    feedbackSentence: "Ja! De bal ligt dichtbij de parasol.",
  }),
  sceneTask({
    id: "lp-016",
    level: 3,
    prompt: "Leg de schelp tussen de bal en het zandkasteel.",
    objectId: "schelp",
    zoneId: "tussen-bal-zandkasteel",
    relation: "tussen",
    anchorObjectIds: ["bal", "zandkasteel"],
    hint: "Tussen betekent in het midden van twee dingen.",
    feedbackSentence: "Knap! De schelp ligt tussen de bal en het zandkasteel.",
  }),
];

export const vocabularyChoiceInstructions: VocabularyChoiceInstruction[] = [
  choiceTask({
    id: "cw-001",
    level: 1,
    prompt: "Waar is de dolfijn?",
    objectId: "dolfijn",
    options: ["dolfijn", "boot"],
    hint: "De dolfijn is het dier dat in de zee springt.",
    distractorStrategy: "different-category",
  }),
  choiceTask({
    id: "cw-002",
    level: 1,
    prompt: "Waar is de boot?",
    objectId: "boot",
    options: ["boot", "bal"],
    hint: "Met een boot kun je varen.",
    distractorStrategy: "different-category",
  }),
  choiceTask({
    id: "cw-003",
    level: 1,
    prompt: "Waar is de bal?",
    objectId: "bal",
    options: ["bal", "schelp"],
    hint: "Met een bal kun je gooien of rollen.",
    distractorStrategy: "same-theme",
  }),
  choiceTask({
    id: "cw-004",
    level: 2,
    prompt: "Waar is de vuurtoren?",
    objectId: "vuurtoren",
    options: ["vuurtoren", "boot", "parasol"],
    hint: "De vuurtoren is een hoge toren op het eiland.",
    distractorStrategy: "same-theme",
  }),
  choiceTask({
    id: "cw-005",
    level: 2,
    prompt: "Waar is de parasol?",
    objectId: "parasol",
    options: ["parasol", "schelp", "krab"],
    hint: "Een parasol geeft schaduw op het strand.",
    distractorStrategy: "same-theme",
  }),
  choiceTask({
    id: "cw-006",
    level: 2,
    prompt: "Waar is de vlieger?",
    objectId: "vlieger",
    options: ["vlieger", "vliegtuig", "boot"],
    hint: "Een vlieger hangt aan een touw en vliegt in de wind.",
    distractorStrategy: "same-theme",
  }),
  choiceTask({
    id: "cw-007",
    level: 2,
    prompt: "Waar is de krab?",
    objectId: "krab",
    options: ["krab", "dolfijn", "schelp"],
    hint: "De krab is een dier met scharen.",
    distractorStrategy: "same-category",
  }),
  choiceTask({
    id: "cw-008",
    level: 2,
    prompt: "Waar is de handdoek?",
    objectId: "handdoek",
    options: ["handdoek", "parasol", "bal"],
    hint: "Op een handdoek kun je zitten of liggen.",
    distractorStrategy: "same-category",
  }),
  choiceTask({
    id: "cw-009",
    level: 3,
    prompt: "Waar is de schelp?",
    objectId: "schelp",
    options: ["schelp", "krab", "bal", "zandkasteel"],
    hint: "Een schelp kun je op het strand vinden.",
    distractorStrategy: "same-theme",
  }),
  choiceTask({
    id: "cw-010",
    level: 3,
    prompt: "Waar is het zandkasteel?",
    objectId: "zandkasteel",
    options: ["zandkasteel", "vuurtoren", "parasol", "bal"],
    hint: "Een zandkasteel maak je van zand.",
    distractorStrategy: "same-theme",
  }),
  choiceTask({
    id: "cw-011",
    level: 3,
    prompt: "Waar is het vliegtuig?",
    objectId: "vliegtuig",
    options: ["vliegtuig", "vlieger", "boot", "dolfijn"],
    hint: "Een vliegtuig vliegt hoog in de lucht.",
    distractorStrategy: "same-category",
  }),
  choiceTask({
    id: "cw-012",
    level: 3,
    prompt: "Waar is de zon?",
    objectId: "zon",
    options: ["zon", "bal", "schelp", "parasol"],
    hint: "De zon is geel en staat in de lucht.",
    distractorStrategy: "same-theme",
  }),
];

export const broomRaceInstructions: BroomRaceInstruction[] = [
  raceTask({
    id: "br-001",
    level: 1,
    prompt: "Vlieg onder het vliegtuig door.",
    objectIds: ["vliegtuig"],
    zoneIds: ["lucht"],
    concepts: ["onder"],
    raceAction: "fly-under",
    hint: "Stuur de bezem lager dan het vliegtuig.",
    feedbackSentence: "Gelukt! Je vloog onder het vliegtuig.",
  }),
  raceTask({
    id: "br-002",
    level: 1,
    prompt: "Spring over de bal.",
    objectIds: ["bal"],
    zoneIds: ["strand"],
    concepts: ["boven"],
    raceAction: "fly-over",
    hint: "Over betekent boven de bal langs.",
    feedbackSentence: "Ja! Je ging over de bal.",
  }),
  raceTask({
    id: "br-003",
    level: 2,
    prompt: "Ga links langs de vuurtoren.",
    objectIds: ["vuurtoren"],
    zoneIds: ["eiland"],
    concepts: ["links"],
    raceAction: "go-left",
    hint: "Links is de kant van je linkerhand.",
    feedbackSentence: "Knap! Je ging links langs de vuurtoren.",
  }),
  raceTask({
    id: "br-004",
    level: 2,
    prompt: "Ga rechts langs de boot.",
    objectIds: ["boot"],
    zoneIds: ["zee"],
    concepts: ["rechts"],
    raceAction: "go-right",
    hint: "Rechts is de kant van je rechterhand.",
    feedbackSentence: "Goed! Je ging rechts langs de boot.",
  }),
  raceTask({
    id: "br-005",
    level: 2,
    prompt: "Pak de schelp naast de boot.",
    objectIds: ["schelp", "boot"],
    zoneIds: ["zee", "strand"],
    concepts: ["naast"],
    raceAction: "collect",
    hint: "Zoek de schelp dicht bij de boot.",
    feedbackSentence: "Mooi! Je pakte de schelp naast de boot.",
  }),
  raceTask({
    id: "br-006",
    level: 2,
    prompt: "Vlieg tussen de parasol en het zandkasteel.",
    objectIds: ["parasol", "zandkasteel"],
    zoneIds: ["tussen-bal-zandkasteel"],
    concepts: ["tussen"],
    raceAction: "fly-between",
    hint: "Tussen betekent in het midden van twee dingen.",
    feedbackSentence: "Gelukt! Je vloog tussen de parasol en het zandkasteel.",
  }),
  raceTask({
    id: "br-007",
    level: 2,
    prompt: "Pak de dolfijnster in de zee.",
    objectIds: ["dolfijn"],
    zoneIds: ["zee"],
    concepts: ["in"],
    raceAction: "collect",
    hint: "De dolfijnster ligt in het water.",
    feedbackSentence: "Ja! Je pakte de dolfijnster in de zee.",
  }),
  raceTask({
    id: "br-008",
    level: 3,
    prompt: "Vlieg boven de krab.",
    objectIds: ["krab"],
    zoneIds: ["strand"],
    concepts: ["boven"],
    raceAction: "fly-over",
    hint: "Stuur de bezem hoger dan de krab.",
    feedbackSentence: "Knap! Je vloog boven de krab.",
  }),
  raceTask({
    id: "br-009",
    level: 3,
    prompt: "Vlieg door het midden.",
    objectIds: [],
    zoneIds: ["midden-strand"],
    concepts: ["midden"],
    raceAction: "collect",
    hint: "Midden is tussen links en rechts.",
    feedbackSentence: "Goed! Je vloog door het midden.",
  }),
  raceTask({
    id: "br-010",
    level: 3,
    prompt: "Pak eerst de zonster en daarna de schelp.",
    objectIds: ["zon", "schelp"],
    zoneIds: ["lucht", "strand"],
    concepts: ["boven", "op"],
    raceAction: "follow-sequence",
    hint: "Eerst komt de zon, daarna komt de schelp.",
    feedbackSentence: "Mooi! Je volgde de goede volgorde.",
    tags: ["sequence", "eerst-daarna"],
  }),
];

export const beachInstructions: GameInstruction[] = [
  ...sceneBuilderInstructions,
  ...vocabularyChoiceInstructions,
  ...broomRaceInstructions,
];

export const beachRewards: BroomReward[] = [
  {
    id: "blue-broom",
    type: "broom",
    name: "Blauwe Bezem",
    description: "Een rustige blauwe beginnersbezem.",
    assetId: "broom-03-dolphin",
    unlockAfterWordStars: 5,
  },
  {
    id: "dolphin-sticker",
    type: "sticker",
    name: "Dolfijn Sticker",
    description: "Een vrolijke dolfijnsticker voor het stickerboek.",
    assetId: "dolfijn",
    unlockAfterWordStars: 10,
  },
  {
    id: "beach-trail",
    type: "broom-trail",
    name: "Strand Sprankel",
    description: "Een zachte strandtrail achter de bezem.",
    assetId: "broom-02-beach",
    unlockAfterWordStars: 15,
  },
  {
    id: "star-mascot-badge",
    type: "sticker",
    name: "Ster Helper",
    description: "Een mascottesticker voor goede oefenrondes.",
    assetId: "mascot-07-ui-icon",
    unlockAfterWordStars: 20,
  },
];

export const beachWorld: GameWorld = {
  id: "beach-world-1",
  name: "Strandwereld",
  theme: "strand",
  recommendedAgeLabel: "4-7 jaar",
  spatialConcepts: beachSpatialConcepts,
  objects: beachObjects,
  zones: beachZones,
  instructions: beachInstructions,
  rewards: beachRewards,
};

export const firstDemoInstructionIds = beachInstructions.map(
  (instruction) => instruction.id,
);
