import type { GameWorld } from "./types";

export const beachWorld: GameWorld = {
  id: "beach-world-1",
  name: "Strandwereld",
  theme: "strand",
  recommendedAgeLabel: "4-7 jaar",
  spatialConcepts: ["in", "op", "naast", "onder", "boven"],
  objects: [
    {
      id: "dolfijn",
      label: "dolfijn",
      pluralLabel: "dolfijnen",
      category: "dieren",
      emoji: "🐬",
      description: "Een dolfijn die in de zee zwemt.",
      vocabularyLevel: 2,
    },
    {
      id: "boot",
      label: "boot",
      pluralLabel: "boten",
      category: "voertuigen",
      emoji: "⛵",
      description: "Een boot op het water.",
      vocabularyLevel: 1,
    },
    {
      id: "vuurtoren",
      label: "vuurtoren",
      pluralLabel: "vuurtorens",
      category: "plekken",
      emoji: "🗼",
      description: "Een hoge toren op het eiland.",
      vocabularyLevel: 3,
    },
    {
      id: "vliegtuig",
      label: "vliegtuig",
      pluralLabel: "vliegtuigen",
      category: "voertuigen",
      emoji: "✈️",
      description: "Een vliegtuig in de lucht.",
      vocabularyLevel: 2,
    },
    {
      id: "vlieger",
      label: "vlieger",
      pluralLabel: "vliegers",
      category: "strandspullen",
      emoji: "🪁",
      description: "Een vlieger boven het strand.",
      vocabularyLevel: 2,
    },
    {
      id: "bal",
      label: "bal",
      pluralLabel: "ballen",
      category: "strandspullen",
      emoji: "⚽",
      description: "Een bal op het strand.",
      vocabularyLevel: 1,
    },
    {
      id: "parasol",
      label: "parasol",
      pluralLabel: "parasols",
      category: "strandspullen",
      emoji: "⛱️",
      description: "Een parasol die schaduw geeft.",
      vocabularyLevel: 2,
    },
    {
      id: "schelp",
      label: "schelp",
      pluralLabel: "schelpen",
      category: "strandspullen",
      emoji: "🐚",
      description: "Een schelp op het zand.",
      vocabularyLevel: 2,
    },
    {
      id: "krab",
      label: "krab",
      pluralLabel: "krabben",
      category: "dieren",
      emoji: "🦀",
      description: "Een krab op het strand.",
      vocabularyLevel: 2,
    },
    {
      id: "zandkasteel",
      label: "zandkasteel",
      pluralLabel: "zandkastelen",
      category: "strandspullen",
      emoji: "🏰",
      description: "Een kasteel van zand.",
      vocabularyLevel: 2,
    },
  ],
  zones: [
    {
      id: "zee",
      label: "zee",
      description: "Het watergebied in de scene.",
      x: 0,
      y: 48,
      width: 100,
      height: 30,
    },
    {
      id: "strand",
      label: "strand",
      description: "Het zandgebied onderaan de scene.",
      x: 0,
      y: 68,
      width: 100,
      height: 32,
    },
    {
      id: "lucht",
      label: "lucht",
      description: "De lucht boven de zee en het strand.",
      x: 0,
      y: 0,
      width: 100,
      height: 42,
    },
    {
      id: "eiland",
      label: "eiland",
      description: "Klein eiland rechts in de zee.",
      x: 68,
      y: 42,
      width: 24,
      height: 20,
    },
    {
      id: "parasol-plek",
      label: "plek naast de parasol",
      description: "Een plek op het strand naast de parasol.",
      x: 52,
      y: 70,
      width: 20,
      height: 18,
    },
    {
      id: "onder-parasol",
      label: "onder de parasol",
      description: "Een plek direct onder de parasol.",
      x: 42,
      y: 76,
      width: 18,
      height: 16,
    },
  ],
  instructions: [
    {
      id: "lp-001",
      mode: "listen-and-place",
      level: 1,
      prompt: "Zet de boot in het water.",
      audioText: "Zet de boot in het water.",
      targetObjectIds: ["boot"],
      targetZoneIds: ["zee"],
      spatialConcepts: ["in"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "Zoek de boot en sleep hem naar de zee.",
      feedback: "Goed zo! De boot vaart in het water. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "lp-002",
      mode: "listen-and-place",
      level: 1,
      prompt: "Zet de dolfijn in de zee.",
      audioText: "Zet de dolfijn in de zee.",
      targetObjectIds: ["dolfijn"],
      targetZoneIds: ["zee"],
      spatialConcepts: ["in"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "De dolfijn zwemt in het water.",
      feedback: "Mooi! De dolfijn zwemt in de zee. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "lp-003",
      mode: "listen-and-place",
      level: 1,
      prompt: "Zet de bal op het strand.",
      audioText: "Zet de bal op het strand.",
      targetObjectIds: ["bal"],
      targetZoneIds: ["strand"],
      spatialConcepts: ["op"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "De bal hoort op het zand.",
      feedback: "Ja! De bal ligt op het strand. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "lp-004",
      mode: "listen-and-place",
      level: 1,
      prompt: "Zet de vuurtoren op het eiland.",
      audioText: "Zet de vuurtoren op het eiland.",
      targetObjectIds: ["vuurtoren"],
      targetZoneIds: ["eiland"],
      spatialConcepts: ["op"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "Kijk naar het eiland rechts in de zee.",
      feedback: "Goed gedaan! De vuurtoren staat op het eiland. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "lp-005",
      mode: "listen-and-place",
      level: 1,
      prompt: "Zet het vliegtuig boven de boot.",
      audioText: "Zet het vliegtuig boven de boot.",
      targetObjectIds: ["vliegtuig"],
      targetZoneIds: ["lucht"],
      spatialConcepts: ["boven"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "Boven is in de lucht.",
      feedback: "Knap! Het vliegtuig vliegt boven de boot. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "lp-006",
      mode: "listen-and-place",
      level: 2,
      prompt: "Leg de schelp naast de bal.",
      audioText: "Leg de schelp naast de bal.",
      targetObjectIds: ["schelp"],
      targetZoneIds: ["strand"],
      spatialConcepts: ["naast"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "Naast betekent dichtbij aan de zijkant.",
      feedback: "Goed geprobeerd! De schelp ligt naast de bal. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "lp-007",
      mode: "listen-and-place",
      level: 2,
      prompt: "Zet de parasol naast het zandkasteel.",
      audioText: "Zet de parasol naast het zandkasteel.",
      targetObjectIds: ["parasol"],
      targetZoneIds: ["parasol-plek"],
      spatialConcepts: ["naast"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "Sleep de parasol naar de plek naast het zandkasteel.",
      feedback: "Mooi! De parasol staat naast het zandkasteel. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "lp-008",
      mode: "listen-and-place",
      level: 2,
      prompt: "Zet de krab onder de parasol.",
      audioText: "Zet de krab onder de parasol.",
      targetObjectIds: ["krab"],
      targetZoneIds: ["onder-parasol"],
      spatialConcepts: ["onder"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "Onder is beneden de parasol.",
      feedback: "Ja! De krab zit onder de parasol. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "cw-001",
      mode: "choose-word",
      level: 1,
      prompt: "Waar is de dolfijn?",
      audioText: "Waar is de dolfijn?",
      targetObjectIds: ["dolfijn"],
      targetZoneIds: [],
      spatialConcepts: [],
      languageDomains: ["receptive-vocabulary"],
      answerOptions: ["dolfijn", "boot"],
      hint: "De dolfijn is het dier dat in de zee springt.",
      feedback: "Ja, dat is de dolfijn. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "cw-002",
      mode: "choose-word",
      level: 1,
      prompt: "Waar is de boot?",
      audioText: "Waar is de boot?",
      targetObjectIds: ["boot"],
      targetZoneIds: [],
      spatialConcepts: [],
      languageDomains: ["receptive-vocabulary"],
      answerOptions: ["boot", "bal"],
      hint: "Met een boot kun je varen.",
      feedback: "Goed! Dat is de boot. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "cw-003",
      mode: "choose-word",
      level: 2,
      prompt: "Waar is de vuurtoren?",
      audioText: "Waar is de vuurtoren?",
      targetObjectIds: ["vuurtoren"],
      targetZoneIds: [],
      spatialConcepts: [],
      languageDomains: ["receptive-vocabulary"],
      answerOptions: ["vuurtoren", "boot", "parasol"],
      hint: "De vuurtoren is een hoge toren op het eiland.",
      feedback: "Knap! Dat is de vuurtoren. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "cw-004",
      mode: "choose-word",
      level: 2,
      prompt: "Waar is de parasol?",
      audioText: "Waar is de parasol?",
      targetObjectIds: ["parasol"],
      targetZoneIds: [],
      spatialConcepts: [],
      languageDomains: ["receptive-vocabulary"],
      answerOptions: ["parasol", "schelp", "krab"],
      hint: "Een parasol geeft schaduw op het strand.",
      feedback: "Ja! Dat is de parasol. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "cw-005",
      mode: "choose-word",
      level: 3,
      prompt: "Waar is de schelp?",
      audioText: "Waar is de schelp?",
      targetObjectIds: ["schelp"],
      targetZoneIds: [],
      spatialConcepts: [],
      languageDomains: ["receptive-vocabulary"],
      answerOptions: ["schelp", "krab", "bal", "zandkasteel"],
      hint: "Een schelp kun je op het strand vinden.",
      feedback: "Goed zo! Dat is de schelp. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "br-001",
      mode: "broom-escape-run",
      level: 1,
      prompt: "Vlieg onder het vliegtuig door.",
      audioText: "Vlieg onder het vliegtuig door.",
      targetObjectIds: ["vliegtuig"],
      targetZoneIds: ["lucht"],
      spatialConcepts: ["onder"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "Stuur de bezem lager dan het vliegtuig.",
      feedback: "Gelukt! Je vloog onder het vliegtuig. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "br-002",
      mode: "broom-escape-run",
      level: 1,
      prompt: "Vlieg boven de boot.",
      audioText: "Vlieg boven de boot.",
      targetObjectIds: ["boot"],
      targetZoneIds: ["zee"],
      spatialConcepts: ["boven"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "Stuur de bezem hoger dan de boot.",
      feedback: "Ja! Je vloog boven de boot. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "br-003",
      mode: "broom-escape-run",
      level: 2,
      prompt: "Pak de schelp naast de bal.",
      audioText: "Pak de schelp naast de bal.",
      targetObjectIds: ["schelp", "bal"],
      targetZoneIds: ["strand"],
      spatialConcepts: ["naast"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "Zoek de schelp die dicht bij de bal ligt.",
      feedback: "Mooi! Je pakte de schelp naast de bal. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "br-004",
      mode: "broom-escape-run",
      level: 2,
      prompt: "Ga naar de parasol op het strand.",
      audioText: "Ga naar de parasol op het strand.",
      targetObjectIds: ["parasol"],
      targetZoneIds: ["strand"],
      spatialConcepts: ["op"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "De parasol staat op het zand.",
      feedback: "Goed! Je vond de parasol op het strand. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "br-005",
      mode: "broom-escape-run",
      level: 2,
      prompt: "Vlieg langs de vuurtoren op het eiland.",
      audioText: "Vlieg langs de vuurtoren op het eiland.",
      targetObjectIds: ["vuurtoren"],
      targetZoneIds: ["eiland"],
      spatialConcepts: ["op"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "Kijk naar de hoge toren op het eiland.",
      feedback: "Knap! Je vloog langs de vuurtoren. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "lp-009",
      mode: "listen-and-place",
      level: 1,
      prompt: "Zet de vlieger boven het strand.",
      audioText: "Zet de vlieger boven het strand.",
      targetObjectIds: ["vlieger"],
      targetZoneIds: ["lucht"],
      spatialConcepts: ["boven"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "De vlieger hoort hoog in de lucht.",
      feedback: "Goed zo! De vlieger is boven het strand. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "lp-010",
      mode: "listen-and-place",
      level: 1,
      prompt: "Zet het zandkasteel op het strand.",
      audioText: "Zet het zandkasteel op het strand.",
      targetObjectIds: ["zandkasteel"],
      targetZoneIds: ["strand"],
      spatialConcepts: ["op"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "Een zandkasteel staat op het zand.",
      feedback: "Ja! Het zandkasteel staat op het strand. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "lp-011",
      mode: "listen-and-place",
      level: 2,
      prompt: "Zet het vliegtuig boven de vuurtoren.",
      audioText: "Zet het vliegtuig boven de vuurtoren.",
      targetObjectIds: ["vliegtuig"],
      targetZoneIds: ["lucht"],
      spatialConcepts: ["boven"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "Boven betekent hoger dan de vuurtoren.",
      feedback: "Knap! Het vliegtuig vliegt boven de vuurtoren. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "lp-012",
      mode: "listen-and-place",
      level: 2,
      prompt: "Zet de krab naast de schelp.",
      audioText: "Zet de krab naast de schelp.",
      targetObjectIds: ["krab"],
      targetZoneIds: ["strand"],
      spatialConcepts: ["naast"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "Naast betekent dicht bij de schelp.",
      feedback: "Mooi! De krab zit naast de schelp. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "cw-006",
      mode: "choose-word",
      level: 2,
      prompt: "Waar is de vlieger?",
      audioText: "Waar is de vlieger?",
      targetObjectIds: ["vlieger"],
      targetZoneIds: [],
      spatialConcepts: [],
      languageDomains: ["receptive-vocabulary"],
      answerOptions: ["vlieger", "vliegtuig", "boot"],
      hint: "Een vlieger hangt aan een touw en vliegt in de wind.",
      feedback: "Goed! Dat is de vlieger. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "cw-007",
      mode: "choose-word",
      level: 1,
      prompt: "Waar is de bal?",
      audioText: "Waar is de bal?",
      targetObjectIds: ["bal"],
      targetZoneIds: [],
      spatialConcepts: [],
      languageDomains: ["receptive-vocabulary"],
      answerOptions: ["bal", "schelp"],
      hint: "Met een bal kun je gooien of rollen.",
      feedback: "Ja! Dat is de bal. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "cw-008",
      mode: "choose-word",
      level: 2,
      prompt: "Waar is de krab?",
      audioText: "Waar is de krab?",
      targetObjectIds: ["krab"],
      targetZoneIds: [],
      spatialConcepts: [],
      languageDomains: ["receptive-vocabulary"],
      answerOptions: ["krab", "dolfijn", "schelp"],
      hint: "De krab is een dier met scharen.",
      feedback: "Knap! Dat is de krab. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "cw-009",
      mode: "choose-word",
      level: 3,
      prompt: "Waar is het zandkasteel?",
      audioText: "Waar is het zandkasteel?",
      targetObjectIds: ["zandkasteel"],
      targetZoneIds: [],
      spatialConcepts: [],
      languageDomains: ["receptive-vocabulary"],
      answerOptions: ["zandkasteel", "vuurtoren", "parasol", "bal"],
      hint: "Een zandkasteel maak je van zand.",
      feedback: "Mooi! Dat is het zandkasteel. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "br-006",
      mode: "broom-escape-run",
      level: 1,
      prompt: "Vlieg onder de vlieger door.",
      audioText: "Vlieg onder de vlieger door.",
      targetObjectIds: ["vlieger"],
      targetZoneIds: ["lucht"],
      spatialConcepts: ["onder"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "Blijf lager dan de vlieger.",
      feedback: "Gelukt! Je vloog onder de vlieger. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "br-007",
      mode: "broom-escape-run",
      level: 1,
      prompt: "Pak de bal op het strand.",
      audioText: "Pak de bal op het strand.",
      targetObjectIds: ["bal"],
      targetZoneIds: ["strand"],
      spatialConcepts: ["op"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "De bal ligt op het zand.",
      feedback: "Goed gedaan! Je pakte de bal op het strand. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "br-008",
      mode: "broom-escape-run",
      level: 2,
      prompt: "Vlieg boven het zandkasteel.",
      audioText: "Vlieg boven het zandkasteel.",
      targetObjectIds: ["zandkasteel"],
      targetZoneIds: ["strand"],
      spatialConcepts: ["boven"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "Stuur de bezem hoger dan het zandkasteel.",
      feedback: "Ja! Je vloog boven het zandkasteel. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
    {
      id: "br-009",
      mode: "broom-escape-run",
      level: 2,
      prompt: "Pak de krab naast de schelp.",
      audioText: "Pak de krab naast de schelp.",
      targetObjectIds: ["krab", "schelp"],
      targetZoneIds: ["strand"],
      spatialConcepts: ["naast"],
      languageDomains: ["sentence-comprehension", "spatial-concepts", "following-directions"],
      hint: "Zoek de krab dicht bij de schelp.",
      feedback: "Knap! Je pakte de krab naast de schelp. +1 Speed!",
      reward: { speed: 1, wordStars: 1 },
    },
  ],
  rewards: [
    {
      id: "blue-broom",
      type: "broom-color",
      name: "Blauwe Bezem",
      unlockAfterWordStars: 5,
    },
    {
      id: "dolphin-sticker",
      type: "sticker",
      name: "Dolfijn Sticker",
      unlockAfterWordStars: 10,
    },
    {
      id: "beach-star-sticker",
      type: "sticker",
      name: "Strandster Sticker",
      unlockAfterWordStars: 15,
    },
  ],
};

export const firstDemoInstructionIds = beachWorld.instructions.map((instruction) => instruction.id);
