import { defineGameManifest } from "../game-platform/contracts";

const worldCardImageUrl = (fileName: string) =>
  new URL(`./catalog-assets/worlds/${fileName}`, import.meta.url).href;

export const comingSoonGameManifests = [
  defineGameManifest({
    ageRange: { max: 8, min: 4 },
    capabilities: ["audio", "microphone", "offline-package"],
    cardImageUrl: worldCardImageUrl("world-farm.webp"),
    contentVersion: "boerderij-2026.09",
    contractVersion: 1,
    description: "Leer de dieren en spullen van de boerderij kennen: koe, tractor, schuur en meer!",
    icon: "🚜",
    id: "vrolijke-boerderij-avontuur",
    offlinePackages: [],
    releaseStatus: "coming-soon",
    requiredCapabilities: [],
    supportedOrientations: ["portrait", "landscape"],
    themeId: "vocabulary",
    title: "Vrolijke Boerderij-Avontuur",
  }),
  defineGameManifest({
    ageRange: { max: 8, min: 4 },
    capabilities: ["audio", "microphone", "offline-package"],
    cardImageUrl: worldCardImageUrl("world-playground.webp"),
    contentVersion: "speeltuin-2026.09",
    contractVersion: 1,
    description: "Schommel, glijbaan en zandbak: speel en oefen de woorden van de speeltuin!",
    icon: "🛝",
    id: "zonnige-speeltuin-avontuur",
    offlinePackages: [],
    releaseStatus: "coming-soon",
    requiredCapabilities: [],
    supportedOrientations: ["portrait", "landscape"],
    themeId: "vocabulary",
    title: "Zonnige Speeltuin-Avontuur",
  }),
  defineGameManifest({
    ageRange: { max: 8, min: 4 },
    capabilities: ["audio", "microphone", "offline-package"],
    cardImageUrl: worldCardImageUrl("world-school.webp"),
    contentVersion: "school-2026.09",
    contractVersion: 1,
    description: "Boek, schaar en schoolbord: oefen de woorden die je elke dag in de klas ziet!",
    icon: "🎒",
    id: "slimme-school-avontuur",
    offlinePackages: [],
    releaseStatus: "coming-soon",
    requiredCapabilities: [],
    supportedOrientations: ["portrait", "landscape"],
    themeId: "vocabulary",
    title: "Slimme School-Avontuur",
  }),
  defineGameManifest({
    ageRange: { max: 8, min: 4 },
    capabilities: ["audio", "microphone", "offline-package"],
    cardImageUrl: worldCardImageUrl("world-space.webp"),
    contentVersion: "ruimte-2026.09",
    contractVersion: 1,
    description: "Raket, maan en sterren: ontdek de woorden van het heelal!",
    icon: "🚀",
    id: "stoere-ruimte-avontuur",
    offlinePackages: [],
    releaseStatus: "coming-soon",
    requiredCapabilities: [],
    supportedOrientations: ["portrait", "landscape"],
    themeId: "vocabulary",
    title: "Stoere Ruimte-Avontuur",
  }),
  defineGameManifest({
    ageRange: { max: 8, min: 4 },
    capabilities: ["audio", "microphone", "offline-package"],
    cardImageUrl: worldCardImageUrl("world-zoo.webp"),
    contentVersion: "dierentuin-2026.09",
    contractVersion: 1,
    description: "Giraf, pinguïn en krokodil: leer de dieren van de dierentuin benoemen!",
    icon: "🦒",
    id: "wilde-dierentuin-avontuur",
    offlinePackages: [],
    releaseStatus: "coming-soon",
    requiredCapabilities: [],
    supportedOrientations: ["portrait", "landscape"],
    themeId: "vocabulary",
    title: "Wilde Dierentuin-Avontuur",
  }),
  defineGameManifest({
    ageRange: { max: 8, min: 4 },
    capabilities: ["audio"],
    contentVersion: "taal-strand-2026.07",
    contractVersion: 1,
    description: "Oefen woordjes, spelling en klanken op het magische strand!",
    icon: "📖",
    id: "taal-strand-avontuur",
    offlinePackages: [],
    releaseStatus: "coming-soon",
    requiredCapabilities: [],
    supportedOrientations: ["portrait", "landscape"],
    themeId: "language",
    title: "Taal Strand-Avontuur",
  }),
  defineGameManifest({
    ageRange: { max: 8, min: 4 },
    capabilities: ["audio"],
    contentVersion: "rekenen-strand-2026.09",
    contractVersion: 1,
    description: "Tellen, optellen en aftrekken met schelpen, krabben en boten op het strand!",
    icon: "🧮",
    id: "rekenen-strand-avontuur",
    offlinePackages: [],
    releaseStatus: "coming-soon",
    requiredCapabilities: [],
    supportedOrientations: ["portrait", "landscape"],
    themeId: "math",
    title: "Rekenen Strand-Avontuur",
  }),
  defineGameManifest({
    ageRange: { max: 8, min: 4 },
    capabilities: ["audio"],
    contentVersion: "wereld-strand-2026.07",
    contractVersion: 1,
    description: "Ontdek de natuur, zee, dieren en het weer op het strand!",
    icon: "🌍",
    id: "wereld-strand-avontuur",
    offlinePackages: [],
    releaseStatus: "coming-soon",
    requiredCapabilities: [],
    supportedOrientations: ["portrait", "landscape"],
    themeId: "world",
    title: "Wereld Strand-Avontuur",
  }),
] as const;
