import type {
  BroomReward,
  GameInstruction,
  GameWorld,
  LanguageDomain,
  SceneBuilderInstruction,
  SceneObject,
  SceneZone,
  SpatialConcept,
  TaskDifficulty,
  VocabularyChoiceInstruction,
} from "./types";

const assetPath = (fileName: string) => `assets/objects/transparent/${fileName}`;

export const beachSpatialConcepts: SpatialConcept[] = [
  "in",
  "op",
  "onder",
  "boven",
  "naast",
  "tussen",
  "links",
  "rechts",
  "midden",
  "dichtbij",
  "ver weg",
];

export const beachObjects: SceneObject[] = [
  {
    id: "dolfijn",
    label: "dolfijn",
    pluralLabel: "dolfijnen",
    article: "de",
    category: "dieren",
    emoji: "🐬",
    assetId: "dolfijn",
    assetPath: assetPath("dolphin-sticker.png"),
    description: "Een dolfijn die in de zee zwemt.",
    vocabularyLevel: 2,
    tags: ["strand", "dier", "zee", "beweegt"],
  },
  {
    id: "boot",
    label: "boot",
    pluralLabel: "boten",
    article: "de",
    category: "voertuigen",
    emoji: "⛵",
    assetId: "boot",
    assetPath: assetPath("sailboat-sticker.png"),
    description: "Een kleine boot op het water.",
    vocabularyLevel: 1,
    tags: ["strand", "voertuig", "zee", "vaart"],
  },
  {
    id: "vuurtoren",
    label: "vuurtoren",
    pluralLabel: "vuurtorens",
    article: "de",
    category: "plekken",
    emoji: "🗼",
    assetId: "vuurtoren",
    assetPath: assetPath("lighthouse-sticker.png"),
    description: "Een hoge toren op het eiland.",
    vocabularyLevel: 3,
    tags: ["strand", "plek", "eiland", "hoog"],
  },
  {
    id: "vliegtuig",
    label: "vliegtuig",
    pluralLabel: "vliegtuigen",
    article: "het",
    category: "voertuigen",
    emoji: "✈️",
    assetId: "vliegtuig",
    assetPath: assetPath("airplane-sticker.png"),
    description: "Een vliegtuig in de lucht.",
    vocabularyLevel: 2,
    tags: ["lucht", "voertuig", "vliegt"],
  },
  {
    id: "vlieger",
    label: "vlieger",
    pluralLabel: "vliegers",
    article: "de",
    category: "strandspullen",
    emoji: "🪁",
    assetId: "vlieger",
    assetPath: assetPath("kite-sticker.png"),
    description: "Een vlieger boven het strand.",
    vocabularyLevel: 2,
    tags: ["strand", "speelgoed", "lucht"],
  },
  {
    id: "bal",
    label: "bal",
    pluralLabel: "ballen",
    article: "de",
    category: "strandspullen",
    emoji: "⚽",
    assetId: "bal",
    assetPath: assetPath("beach-ball-sticker.png"),
    description: "Een bal op het strand.",
    vocabularyLevel: 1,
    tags: ["strand", "speelgoed", "rond"],
  },
  {
    id: "parasol",
    label: "parasol",
    pluralLabel: "parasols",
    article: "de",
    category: "strandspullen",
    emoji: "⛱️",
    assetId: "parasol",
    assetPath: assetPath("beach-umbrella-sticker.png"),
    description: "Een parasol die schaduw geeft.",
    vocabularyLevel: 2,
    tags: ["strand", "spullen", "schaduw"],
  },
  {
    id: "schelp",
    label: "schelp",
    pluralLabel: "schelpen",
    article: "de",
    category: "strandspullen",
    emoji: "🐚",
    assetId: "schelp",
    assetPath: assetPath("seashells-sticker.png"),
    description: "Een schelp op het zand.",
    vocabularyLevel: 2,
    tags: ["strand", "spullen", "zee"],
  },
  {
    id: "krab",
    label: "krab",
    pluralLabel: "krabben",
    article: "de",
    category: "dieren",
    emoji: "🦀",
    assetId: "krab",
    assetPath: assetPath("crab-sticker.png"),
    description: "Een krab op het strand.",
    vocabularyLevel: 2,
    tags: ["strand", "dier", "scharen"],
  },
  {
    id: "zandkasteel",
    label: "zandkasteel",
    pluralLabel: "zandkastelen",
    article: "het",
    category: "strandspullen",
    emoji: "🏰",
    assetId: "zandkasteel",
    assetPath: assetPath("sandcastle-sticker.png"),
    description: "Een kasteel van zand.",
    vocabularyLevel: 2,
    tags: ["strand", "spullen", "zand"],
  },
  {
    id: "handdoek",
    label: "handdoek",
    pluralLabel: "handdoeken",
    article: "de",
    category: "strandspullen",
    emoji: "▤",
    assetId: "handdoek",
    assetPath: assetPath("beach-towel-sticker.png"),
    description: "Een zachte handdoek op het strand.",
    vocabularyLevel: 1,
    tags: ["strand", "spullen", "liggen"],
  },
  {
    id: "zon",
    label: "zon",
    pluralLabel: "zonnen",
    article: "de",
    category: "natuur",
    emoji: "☀️",
    assetId: "zon",
    assetPath: assetPath("sun-sticker.png"),
    description: "De zon boven de zee.",
    vocabularyLevel: 1,
    tags: ["lucht", "natuur", "warm"],
  },
];

export const beachZones: SceneZone[] = [
  // Basisgebied: lucht
  {
    id: "lucht",
    label: "lucht",
    description: "De lucht boven de zee en het strand.",
    kind: "absolute",
    visualHintPath:
      "M1.9 32.1 L27.7 38.8 L67 38.6 L72.3 31 L81.3 23.8 L98.8 22 L97.8 15.7 L1.5 16.2 Z",
    x: 1.5,
    y: 15.7,
    width: 97.3,
    height: 23.1,
    supportedConcepts: ["boven", "links", "rechts", "midden", "ver weg"],
  },

  // Zee en waterzones
  {
    id: "zee",
    label: "zee",
    description: "Het watergebied in de scene.",
    kind: "absolute",
    visualHintPath:
      "M99 52.2 L88.1 52.5 L76.5 54.4 L65 53.8 L55.8 54.6 L44.7 54 L32.3 55.2 L21.4 55.1 L14.3 54 L0.7 53.3 L0.5 38.8 L63.6 39 L59.2 42.1 L76.2 43.2 L99.3 43.8 Z",
    x: 0.5,
    y: 38.8,
    width: 98.8,
    height: 16.4,
    supportedConcepts: ["in", "op", "links", "rechts", "midden", "dichtbij", "ver weg"],
  },
  {
    id: "links-zee",
    label: "links in zee",
    description: "Linkerkant van de zee.",
    kind: "horizontal",
    visualHintPath: "M1 32.1 L48.8 31.7 L47.5 53.3 L40 54.3 L27.4 55.6 L15.8 53.9 L0.1 53.7 Z",
    x: 0.1,
    y: 31.7,
    width: 48.7,
    height: 23.9,
    supportedConcepts: ["links", "in"],
  },
  {
    id: "boven-zee",
    label: "boven de zee",
    description: "Luchtgebied boven de zee.",
    kind: "relative",
    visualHintPath: "M0.7 31.4 L72.3 31.6 L72.3 16.1 L0.5 16.5 Z",
    x: 0.5,
    y: 16.1,
    width: 71.8,
    height: 15.5,
    supportedConcepts: ["boven", "ver weg"],
  },
  {
    id: "ver-weg-zee",
    label: "ver weg boven zee",
    description: "Een plek ver weg in de lucht boven de zee.",
    kind: "relative",
    visualHintPath: "M0 32.1 L0.2 16.5 L64.1 16.1 L64.3 31.6 Z",
    x: 0.0,
    y: 16.1,
    width: 64.3,
    height: 16.0,
    supportedConcepts: ["ver weg", "boven"],
  },
  {
    id: "eiland",
    label: "eiland",
    description: "Klein eiland rechts in de zee.",
    kind: "landmark",
    visualHintPath:
      "M99.3 43.2 L85.9 43.6 L75 42.8 L60.4 41.9 L64.3 39 L73.3 36.8 L78.4 34.9 L84.2 32.7 L90.3 31.6 L100 30.9 Z",
    x: 60.4,
    y: 30.9,
    width: 39.6,
    height: 12.7,
    supportedConcepts: ["op", "rechts", "ver weg"],
  },

  // Strand en zandzones
  {
    id: "strand",
    label: "strand",
    description: "Het zandgebied onderaan de scene.",
    kind: "absolute",
    visualHintPath:
      "M0 53.8 L7.8 54.4 L15.3 54.1 L25 55.6 L36.4 55.3 L44.4 54.2 L57 55.1 L66 53.9 L77.9 54.8 L86.2 53.6 L91.7 52.9 L99.5 52.8 L98.8 88 L0.5 88.3 Z",
    x: 0.0,
    y: 52.8,
    width: 99.5,
    height: 35.5,
    supportedConcepts: [
      "op",
      "naast",
      "tussen",
      "links",
      "rechts",
      "midden",
      "dichtbij",
      "ver weg",
    ],
  },
  {
    id: "midden-strand",
    label: "midden op het strand",
    description: "Midden van het strand.",
    kind: "horizontal",
    visualHintPath: "M65.3 53.6 L65.3 88.4 L25.2 88.5 L26.2 55.8 L36.4 55.3 L43.2 54 L54.1 55.4 Z",
    x: 25.2,
    y: 53.6,
    width: 40.1,
    height: 34.9,
    supportedConcepts: ["midden", "op"],
  },
  {
    id: "rechts-strand",
    label: "rechts op het strand",
    description: "Rechterkant van het strand.",
    kind: "horizontal",
    visualHintPath: "M66 53.8 L73.8 54.5 L84 53.9 L92.3 52.5 L100 52.7 L98.8 88.1 L66.3 88.3 Z",
    x: 66.0,
    y: 52.5,
    width: 34.0,
    height: 35.8,
    supportedConcepts: ["rechts", "op"],
  },
  // Relationele zones zoals op/naast/dichtbij/tussen bij een ankerobject
  // worden dynamisch berekend met de actuele positie van geplaatste objecten.
];

const directionDomains: LanguageDomain[] = [
  "sentence-comprehension",
  "concepts-and-directions",
  "spatial-language",
  "following-directions",
];

function getPracticeSentence(sentence: string) {
  return sentence.replace(/^(Goed zo!|Mooi!|Ja!|Goed gedaan!)\s*/i, "");
}

const placementFeedback = (sentence: string, concept: SpatialConcept) => ({
  correct: `${sentence} +1 Speed!`,
  almost: `Bijna! Luister nog eens naar het woord '${concept}'.`,
  tryAgain: "Goed geprobeerd. Kijk rustig naar de plek die oplicht.",
  repeatAfterSuccess: getPracticeSentence(sentence),
});

const choiceFeedback = (word: string) => ({
  correct: `Ja, dat is de ${word}. +1 Speed!`,
  almost: `Bijna. Zoek nog eens naar: ${word}.`,
  tryAgain: "Goed geprobeerd. Luister nog een keer en kies opnieuw.",
  repeatAfterSuccess: `Dit is de ${word}.`,
});

function sceneTask(params: {
  id: string;
  level: TaskDifficulty;
  prompt: string;
  objectId: string;
  zoneId: string;
  relation: SpatialConcept;
  anchorObjectIds?: string[];
  hint: string;
  feedbackSentence: string;
  tags?: string[];
}): SceneBuilderInstruction {
  return {
    id: params.id,
    mode: "listen-and-place",
    level: params.level,
    prompt: params.prompt,
    audioText: params.prompt,
    targetObjectIds: [params.objectId, ...(params.anchorObjectIds ?? [])],
    targetZoneIds: [params.zoneId],
    spatialConcepts: [params.relation],
    languageDomains: directionDomains,
    tags: ["mvp", "scene-builder", params.relation, params.objectId, ...(params.tags ?? [])],
    hint: params.hint,
    feedback: `${params.feedbackSentence} +1 Speed!`,
    feedbackCopy: placementFeedback(params.feedbackSentence, params.relation),
    placement: {
      objectId: params.objectId,
      zoneId: params.zoneId,
      relation: params.relation,
      anchorObjectIds: params.anchorObjectIds,
    },
    reward: { speed: 1, wordStars: 1 },
  };
}

function choiceTask(params: {
  id: string;
  level: TaskDifficulty;
  prompt: string;
  objectId: string;
  options: string[];
  hint: string;
  distractorStrategy: VocabularyChoiceInstruction["distractorStrategy"];
}): VocabularyChoiceInstruction {
  const target = beachObjects.find((object) => object.id === params.objectId);
  const targetWord = target?.label ?? params.objectId;

  return {
    id: params.id,
    mode: "choose-word",
    level: params.level,
    prompt: params.prompt,
    audioText: params.prompt,
    targetObjectIds: [params.objectId],
    targetZoneIds: [],
    spatialConcepts: [],
    languageDomains: ["receptive-vocabulary"],
    tags: ["mvp", "choose-word", "receptive-vocabulary", params.objectId],
    hint: params.hint,
    feedback: `Ja, dat is de ${targetWord}. +1 Speed!`,
    feedbackCopy: choiceFeedback(targetWord),
    targetWord,
    answerOptions: params.options,
    choiceCount: params.options.length as 2 | 3 | 4,
    distractorStrategy: params.distractorStrategy,
    reward: { speed: 1, wordStars: 1 },
  };
}

export const sceneBuilderInstructions: SceneBuilderInstruction[] = [
  sceneTask({
    id: "lp-001",
    level: 1,
    prompt: "Zet de boot in de zee.",
    objectId: "boot",
    zoneId: "zee",
    relation: "in",
    hint: "Zoek de boot en sleep hem naar het water.",
    feedbackSentence: "Goed zo! De boot vaart in de zee.",
  }),
  sceneTask({
    id: "lp-002",
    level: 1,
    prompt: "Zet de dolfijn in de zee.",
    objectId: "dolfijn",
    zoneId: "zee",
    relation: "in",
    hint: "De dolfijn zwemt in het water.",
    feedbackSentence: "Mooi! De dolfijn zwemt in de zee.",
  }),
  sceneTask({
    id: "lp-003",
    level: 1,
    prompt: "Zet de bal op het strand.",
    objectId: "bal",
    zoneId: "strand",
    relation: "op",
    hint: "De bal hoort op het zand.",
    feedbackSentence: "Ja! De bal ligt op het strand.",
  }),
  sceneTask({
    id: "lp-004",
    level: 1,
    prompt: "Zet de vuurtoren op het eiland.",
    objectId: "vuurtoren",
    zoneId: "eiland",
    relation: "op",
    hint: "Kijk naar het eiland rechts in de zee.",
    feedbackSentence: "Goed gedaan! De vuurtoren staat op het eiland.",
  }),
  sceneTask({
    id: "lp-005",
    level: 1,
    prompt: "Zet de vlieger boven het strand.",
    objectId: "vlieger",
    zoneId: "lucht",
    relation: "boven",
    hint: "De vlieger hoort hoog in de lucht.",
    feedbackSentence: "Goed zo! De vlieger is boven het strand.",
  }),
  sceneTask({
    id: "lp-006",
    level: 1,
    prompt: "Zet het vliegtuig boven de zee.",
    objectId: "vliegtuig",
    zoneId: "boven-zee",
    relation: "boven",
    hint: "Boven de zee is in de lucht.",
    feedbackSentence: "Knap! Het vliegtuig vliegt boven de zee.",
  }),
  sceneTask({
    id: "lp-007",
    level: 1,
    prompt: "Leg de schelp op het strand.",
    objectId: "schelp",
    zoneId: "strand",
    relation: "op",
    hint: "De schelp ligt op het zand.",
    feedbackSentence: "Ja! De schelp ligt op het strand.",
  }),
  sceneTask({
    id: "lp-008",
    level: 1,
    prompt: "Zet de krab op de handdoek.",
    objectId: "krab",
    zoneId: "handdoek-zone",
    relation: "op",
    anchorObjectIds: ["handdoek"],
    hint: "Zoek de handdoek en zet de krab erop.",
    feedbackSentence: "Goed! De krab zit op de handdoek.",
  }),
  sceneTask({
    id: "lp-009",
    level: 2,
    prompt: "Zet het zandkasteel naast de schelp.",
    objectId: "zandkasteel",
    zoneId: "naast-schelp",
    relation: "naast",
    anchorObjectIds: ["schelp"],
    hint: "Naast betekent dichtbij aan de zijkant.",
    feedbackSentence: "Mooi! Het zandkasteel staat naast de schelp.",
  }),
  sceneTask({
    id: "lp-010",
    level: 2,
    prompt: "Zet de parasol rechts op het strand.",
    objectId: "parasol",
    zoneId: "rechts-strand",
    relation: "rechts",
    hint: "Rechts is de kant van je rechterhand.",
    feedbackSentence: "Ja! De parasol staat rechts op het strand.",
  }),
  sceneTask({
    id: "lp-011",
    level: 2,
    prompt: "Zet de zon boven de zee.",
    objectId: "zon",
    zoneId: "boven-zee",
    relation: "boven",
    hint: "De zon staat hoog in de lucht.",
    feedbackSentence: "Goed zo! De zon staat boven de zee.",
  }),
  sceneTask({
    id: "lp-012",
    level: 2,
    prompt: "Leg de handdoek midden op het strand.",
    objectId: "handdoek",
    zoneId: "midden-strand",
    relation: "midden",
    hint: "Midden is niet links en niet rechts.",
    feedbackSentence: "Knap! De handdoek ligt midden op het strand.",
  }),
  sceneTask({
    id: "lp-013",
    level: 2,
    prompt: "Zet de boot links in de zee.",
    objectId: "boot",
    zoneId: "links-zee",
    relation: "links",
    hint: "Links is de kant van je linkerhand.",
    feedbackSentence: "Goed! De boot vaart links in de zee.",
  }),
  sceneTask({
    id: "lp-014",
    level: 3,
    prompt: "Zet het vliegtuig ver weg boven de zee.",
    objectId: "vliegtuig",
    zoneId: "ver-weg-zee",
    relation: "ver weg",
    hint: "Ver weg is verder van de voorkant van de scene.",
    feedbackSentence: "Mooi! Het vliegtuig vliegt ver weg boven de zee.",
  }),
  sceneTask({
    id: "lp-015",
    level: 3,
    prompt: "Leg de bal dichtbij de parasol.",
    objectId: "bal",
    zoneId: "dichtbij-parasol",
    relation: "dichtbij",
    anchorObjectIds: ["parasol"],
    hint: "Dichtbij betekent niet ver weg.",
    feedbackSentence: "Ja! De bal ligt dichtbij de parasol.",
  }),
  sceneTask({
    id: "lp-016",
    level: 3,
    prompt: "Leg de schelp tussen de bal en het zandkasteel.",
    objectId: "schelp",
    zoneId: "tussen-bal-zandkasteel",
    relation: "tussen",
    anchorObjectIds: ["bal", "zandkasteel"],
    hint: "Tussen betekent in het midden van twee dingen.",
    feedbackSentence: "Knap! De schelp ligt tussen de bal en het zandkasteel.",
  }),
];

export const vocabularyChoiceInstructions: VocabularyChoiceInstruction[] = [
  choiceTask({
    id: "cw-001",
    level: 1,
    prompt: "Waar is de dolfijn?",
    objectId: "dolfijn",
    options: ["dolfijn", "boot"],
    hint: "De dolfijn is het dier dat in de zee springt.",
    distractorStrategy: "different-category",
  }),
  choiceTask({
    id: "cw-002",
    level: 1,
    prompt: "Waar is de boot?",
    objectId: "boot",
    options: ["boot", "bal"],
    hint: "Met een boot kun je varen.",
    distractorStrategy: "different-category",
  }),
  choiceTask({
    id: "cw-003",
    level: 1,
    prompt: "Waar is de bal?",
    objectId: "bal",
    options: ["bal", "schelp"],
    hint: "Met een bal kun je gooien of rollen.",
    distractorStrategy: "same-theme",
  }),
  choiceTask({
    id: "cw-004",
    level: 2,
    prompt: "Waar is de vuurtoren?",
    objectId: "vuurtoren",
    options: ["vuurtoren", "boot", "parasol"],
    hint: "De vuurtoren is een hoge toren op het eiland.",
    distractorStrategy: "same-theme",
  }),
  choiceTask({
    id: "cw-005",
    level: 2,
    prompt: "Waar is de parasol?",
    objectId: "parasol",
    options: ["parasol", "schelp", "krab"],
    hint: "Een parasol geeft schaduw op het strand.",
    distractorStrategy: "same-theme",
  }),
  choiceTask({
    id: "cw-006",
    level: 2,
    prompt: "Waar is de vlieger?",
    objectId: "vlieger",
    options: ["vlieger", "vliegtuig", "boot"],
    hint: "Een vlieger hangt aan een touw en vliegt in de wind.",
    distractorStrategy: "same-theme",
  }),
  choiceTask({
    id: "cw-007",
    level: 2,
    prompt: "Waar is de krab?",
    objectId: "krab",
    options: ["krab", "dolfijn", "schelp"],
    hint: "De krab is een dier met scharen.",
    distractorStrategy: "same-category",
  }),
  choiceTask({
    id: "cw-008",
    level: 2,
    prompt: "Waar is de handdoek?",
    objectId: "handdoek",
    options: ["handdoek", "parasol", "bal"],
    hint: "Op een handdoek kun je zitten of liggen.",
    distractorStrategy: "same-category",
  }),
  choiceTask({
    id: "cw-009",
    level: 3,
    prompt: "Waar is de schelp?",
    objectId: "schelp",
    options: ["schelp", "krab", "bal", "zandkasteel"],
    hint: "Een schelp kun je op het strand vinden.",
    distractorStrategy: "same-theme",
  }),
  choiceTask({
    id: "cw-010",
    level: 3,
    prompt: "Waar is het zandkasteel?",
    objectId: "zandkasteel",
    options: ["zandkasteel", "vuurtoren", "parasol", "bal"],
    hint: "Een zandkasteel maak je van zand.",
    distractorStrategy: "same-theme",
  }),
  choiceTask({
    id: "cw-011",
    level: 3,
    prompt: "Waar is het vliegtuig?",
    objectId: "vliegtuig",
    options: ["vliegtuig", "vlieger", "boot", "dolfijn"],
    hint: "Een vliegtuig vliegt hoog in de lucht.",
    distractorStrategy: "same-category",
  }),
  choiceTask({
    id: "cw-012",
    level: 3,
    prompt: "Waar is de zon?",
    objectId: "zon",
    options: ["zon", "bal", "schelp", "parasol"],
    hint: "De zon is geel en staat in de lucht.",
    distractorStrategy: "same-theme",
  }),
];

export const beachInstructions: GameInstruction[] = [
  ...sceneBuilderInstructions,
  ...vocabularyChoiceInstructions,
];

export const beachRewards: BroomReward[] = [
  {
    id: "blue-broom",
    type: "broom",
    name: "Blauwe Bezem",
    description: "Een rustige blauwe beginnersbezem.",
    assetId: "broom-03-dolphin",
    unlockAfterWordStars: 5,
  },
  {
    id: "dolphin-sticker",
    type: "sticker",
    name: "Dolfijn Sticker",
    description: "Een vrolijke dolfijnsticker voor het stickerboek.",
    assetId: "dolfijn",
    unlockAfterWordStars: 10,
  },
  {
    id: "beach-trail",
    type: "broom-trail",
    name: "Strand Sprankel",
    description: "Een zachte strandtrail achter de bezem.",
    assetId: "broom-02-beach",
    unlockAfterWordStars: 15,
  },
  {
    id: "star-mascot-badge",
    type: "sticker",
    name: "Ster Helper",
    description: "Een mascottesticker voor goede oefenrondes.",
    assetId: "mascot-07-ui-icon",
    unlockAfterWordStars: 20,
  },
];

export const beachWorld: GameWorld = {
  id: "beach-world-1",
  name: "Strandwereld",
  theme: "strand",
  recommendedAgeLabel: "4-7 jaar",
  spatialConcepts: beachSpatialConcepts,
  objects: beachObjects,
  zones: beachZones,
  instructions: beachInstructions,
  rewards: beachRewards,
};

export const firstDemoInstructionIds = beachInstructions.map((instruction) => instruction.id);
